// Region 5 — 戌吊
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone05: ZoneConfig = {
    id: 5, name: '戌吊',
    backgroundImage: 'bg_zone_05',
    backgroundMode: 'cover',
    groundColor: 0x665555,
    npcs: [
      { x: 0.45, y: 0.35, name: '志波岩鹫', role: 'merchant', dialogue: [
        { speaker: '志波岩鹫', text: '姐姐让我看店。戌吊的装备比润林安还强一点，别小看！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(3, '戌吊', ['inata_hat', 'inata_armor', 'inata_bracer', 'inata_boots', 'inata_belt', 'inata_ring', 'inata_necklace', 'inata_charm', 'inata_pendant']) },
      { x: 0.7, y: 0.5, name: '吉良井鹤', role: 'quest', dialogue: [
        { speaker: '吉良井鹤', text: '戌吊附近的虚越来越强了。帮我清理几只，我推荐你参加始解试炼。', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '戌吊的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '戌吊兵器师', role: 'enhance', dialogue: [{ speaker: '戌吊兵器师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '雀部长次郎', role: 'side_quest', dialogue: [
        { speaker: '雀部长次郎', text: '总队长山本元柳斋大人的斩魄刀——流刃若火，是炎系最强。帮我收集灵脉。' },
      ]},
      { x: 0.65, y: 0.8, name: '伊势七绪', role: 'side_quest', dialogue: [
        { speaker: '伊势七绪', text: '八番队的文书工作……帮我击败几只暴走虚，我给你写推荐信。' },
      ]},
      { x: 0.15, y: 0.5, name: '浮竹十四郎', role: 'lore', dialogue: [
        { speaker: '浮竹十四郎', text: '始解——斩魄刀的第一次解放。你需要找到刀的名字。' },
        { speaker: '浮竹十四郎', text: '草鹿在东边。那里有更强大的死神在等待试炼者。' },
      ]},
      { x: 0.8, y: 0.65, name: '京乐春水', role: 'lore', dialogue: [
        { speaker: '京乐春水', text: '花天狂骨——我的斩魄刀。始解后能将孩童的游戏化为现实。' },
        { speaker: '京乐春水', text: '静灵庭在北边。完成始解后就能进入——但先过了草鹿那关。' },
      ]},
    ],
    enemies: [

      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.18, y: 0.09 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.14, y: 0.45 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.64, y: 0.09 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.52, y: 0.68 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.8, y: 0.5 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.3, y: 0.8 },
      // ── 区域Boss（多尔多尼） ──
      { name: '多尔多尼', type: '妖将', element: '土', x: 0.93, y: 0.88, isBoss: true },
      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.06, y: 0.08 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.51, y: 0.37 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.95, y: 0.62 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.27, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.36 },
      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.05, y: 0.92 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.49, y: 0.08 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.95, y: 0.35 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.27, y: 0.92 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.73, y: 0.08 },
      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.07, y: 0.65 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.51, y: 0.91 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.93, y: 0.08 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.27, y: 0.64 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.71, y: 0.92 },
      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.06, y: 0.35 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.49, y: 0.61 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.27, y: 0.37 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.72, y: 0.61 },
      { name: '流魂街暴徒', type: '杂妖', element: '土', x: 0.05, y: 0.09 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.53, y: 0.34 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.93, y: 0.67 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.25, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.75, y: 0.39 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.05, y: 0.9 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.47, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.95, y: 0.37 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.3, y: 0.92 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.75, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.05, y: 0.62 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.51, y: 0.92 },
    ],
    gathering: [
      { x: 0.21, y: 0.27, type: '灵脉' },
      { x: 0.93, y: 0.9, type: '矿脉' },
      { x: 0.61, y: 0.27, type: '药草' },
      { x: 0.3, y: 0.49, type: '灵脉' },
      { x: 0.94, y: 0.81, type: '灵木' },
      { x: 0.9, y: 0.27, type: '灵木' },
      { x: 0.51, y: 0.16, type: '灵木' },
      { x: 0.13, y: 0.5, type: '灵脉' },
      { x: 0.08, y: 0.1, type: '灵脉' },
      { x: 0.5, y: 0.36, type: '矿脉' },
      { x: 0.95, y: 0.66, type: '药草' },
      { x: 0.28, y: 0.09, type: '灵脉' },
      { x: 0.73, y: 0.35, type: '灵木' },
      { x: 0.07, y: 0.9, type: '灵木' },
      { x: 0.5, y: 0.11, type: '灵木' },
      { x: 0.95, y: 0.37, type: '灵脉' },
      { x: 0.3, y: 0.9, type: '灵脉' },
      { x: 0.72, y: 0.08, type: '矿脉' },
      { x: 0.05, y: 0.64, type: '药草' },
      { x: 0.48, y: 0.91, type: '灵脉' },
      { x: 0.95, y: 0.08, type: '灵木' },
      { x: 0.27, y: 0.66, type: '灵木' },
      { x: 0.74, y: 0.92, type: '灵木' },
      { x: 0.05, y: 0.35, type: '灵脉' },
      { x: 0.5, y: 0.65, type: '灵脉' },
      { x: 0.95, y: 0.89, type: '矿脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 4, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 6, targetX: 0.08, targetY: 0.5 },
    ],
  };
