// Region 4 — 润林安
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone04: ZoneConfig = {
    id: 4, name: '润林安',
    backgroundImage: 'bg_zone_04',
    backgroundMode: 'cover',
    groundColor: 0x665544,
    npcs: [
      { x: 0.5, y: 0.2, name: '志波空鹤', role: 'merchant', dialogue: [
        { speaker: '志波空鹤', text: '花火和武器都在我这。流魂街最好的装备店！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(2, '流魂', ['leather_hat', 'leather_armor', 'leather_bracer', 'leather_boots', 'leather_belt', 'copper_ring', 'bone_necklace', 'leather_charm', 'feather_pendant']) },
      { x: 0.75, y: 0.5, name: '斑目一角', role: 'quest', dialogue: [
        { speaker: '斑目一角', text: '喂！新人！想进静灵庭？先打几场让我看看你的本事！', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.2, y: 0.85, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '流魂街的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '润林安锻造师', role: 'enhance', dialogue: [{ speaker: '润林安锻造师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.35, y: 0.4, name: '绫濑川弓亲', role: 'side_quest', dialogue: [
        { speaker: '绫濑川弓亲', text: '我需要5株灵木来制作新的武器配饰。帮我收集一些。' },
      ]},
      { x: 0.7, y: 0.2, name: '桧佐木修兵', role: 'side_quest', dialogue: [
        { speaker: '桧佐木修兵', text: '流魂街的强盗越来越嚣张了。帮我清理几个。' },
      ]},
      { x: 0.85, y: 0.7, name: '浮竹十四郎', role: 'lore', dialogue: [
        { speaker: '浮竹十四郎', text: '斩魄刀是死神的灵魂。始解的试炼在静灵庭南侧……去那里吧。' },
        { speaker: '浮竹十四郎', text: '我见过无数把斩魄刀。每把都有自己的故事——你也会找到属于你的。' },
      ]},
      { x: 0.25, y: 0.6, name: '山田花太郎', role: 'lore', dialogue: [
        { speaker: '山田花太郎', text: '你也有斩魄刀吗？每把刀都有自己的名字。呼唤它，它就会回应。' },
        { speaker: '山田花太郎', text: '始解是斩魄刀的第一次解放。你需要完成试炼才能听到刀的声音。' },
      ]},
    ],
    enemies: [

      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.3, y: 0.2 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 1.5, y: 0.3 }, { name: '暴走虚', type: '杂妖', element: '无', x: 0.7, y: 0.5 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 1.9, y: 0.7 }, { name: '叛逆队员', type: '杂妖', element: '无', x: 2.2, y: 0.4 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.5, y: 0.75 }, { name: '流魂街强盗', type: '杂妖', element: '土', x: 2.5, y: 0.6 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 1.2, y: 0.8 }, { name: '大虚·基利安', type: '恶妖', element: '无', x: 2.8, y: 0.3 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.9, y: 0.15 },
      // ── 区域Boss（萧隆·库方） ──
      { name: '萧隆·库方', type: '妖将', element: '风', x: 0.93, y: 0.88, isBoss: true },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.07, y: 0.08 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.52, y: 0.34 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.93, y: 0.66 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.28, y: 0.1 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.71, y: 0.33 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.49, y: 0.09 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.94, y: 0.37 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.27, y: 0.89 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.7, y: 0.08 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.05, y: 0.64 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.52, y: 0.92 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.95, y: 0.08 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.28, y: 0.67 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.72, y: 0.89 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.07, y: 0.38 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.48, y: 0.66 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.93, y: 0.92 },
      { name: '流魂街强盗', type: '杂妖', element: '土', x: 0.27, y: 0.36 },
      { name: '暴走虚', type: '杂妖', element: '无', x: 0.7, y: 0.64 },
      { name: '叛逆队员', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.47, y: 0.39 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.93, y: 0.61 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.3, y: 0.1 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.74, y: 0.39 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.07, y: 0.9 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.49, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.92, y: 0.38 },
    ],
    gathering: [
      { x: 0.15, y: 0.25, type: '灵木' },
      { x: 0.4, y: 0.35, type: '矿脉' },
      { x: 0.65, y: 0.55, type: '药草' },
      { x: 0.85, y: 0.8, type: '灵木' },
      { x: 1.2, y: 0.3, type: '矿脉' },
      { x: 1.5, y: 0.7, type: '药草' },
      { x: 1.8, y: 0.4, type: '灵木' },
      { x: 2.2, y: 0.8, type: '矿脉' },
      { x: 2.6, y: 0.25, type: '药草' },
      { x: 0.3, y: 0.65, type: '灵脉' },
      { x: 1.7, y: 0.15, type: '灵木' },
      { x: 2, y: 0.6, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '灵木' },
      { x: 0.5, y: 0.33, type: '矿脉' },
      { x: 0.92, y: 0.64, type: '药草' },
      { x: 0.29, y: 0.1, type: '灵木' },
      { x: 0.71, y: 0.36, type: '矿脉' },
      { x: 0.05, y: 0.91, type: '药草' },
      { x: 0.53, y: 0.09, type: '灵木' },
      { x: 0.92, y: 0.39, type: '矿脉' },
      { x: 0.26, y: 0.92, type: '药草' },
      { x: 0.75, y: 0.1, type: '灵脉' },
      { x: 0.05, y: 0.67, type: '灵木' },
      { x: 0.5, y: 0.92, type: '灵脉' },
      { x: 0.95, y: 0.08, type: '灵木' },
      { x: 0.3, y: 0.65, type: '矿脉' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 3, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 5, targetX: 0.08, targetY: 0.5 },
    ],
  };
