// Region 18 — 银架城
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone18: ZoneConfig = {
    id: 18, name: '银架城',
    backgroundImage: 'bg_zone_18',
    backgroundMode: 'cover',
    groundColor: 0x445577,
    npcs: [
      { x: 0.45, y: 0.35, id: 'npc_m16', role: 'merchant', dialogue: [
        { speaker: '孤影集', text: '银架城的宝库——全知全能所见的一切珍宝。拿去吧。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(9, '银架', ['silbern_hat', 'silbern_armor', 'silbern_bracer', 'silbern_boots', 'silbern_belt', 'silbern_ring', 'silbern_necklace', 'silbern_charm', 'silbern_pendant']) },
      { x: 0.7, y: 0.5, id: 'npc_m14', role: 'quest', dialogue: [
        { speaker: '天衡阁', text: '圣文字的最终试炼——在银架城接受友哈巴赫大人的圣别。准备好了吗？', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.2, id: 'sys_portal_shadow', name: '影之领域', role: 'return_point', dialogue: [
        { speaker: '影之领域', text: '银架城的传送门。北边通往地狱。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.8, y: 0.55, id: 'sys_board', name: '任务公告板', role: 'quest_board', dialogue: [
        { speaker: '任务公告板', text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f18', role: 'enhance', dialogue: [{ speaker: '银架工', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, id: 'npc_s41', role: 'side_quest', dialogue: [
        { speaker: '优哈巴哈的书记', text: '圣文字的记录需要灵脉墨水。帮我采集，我给你查看权限。' },
      ]},
      { x: 0.65, y: 0.8, id: 'npc_s40', role: 'side_quest', dialogue: [
        { speaker: '杰拉德', text: '奇迹需要信仰。帮我击败几只星十字骑士·长，证明你的信仰。' },
      ]},
      { x: 0.15, y: 0.5, id: 'npc_s39', role: 'lore', dialogue: [
        { speaker: '石田龙弦', text: '银架城——无形帝国的核心。友哈巴赫的力量源泉在这里。' },
        { speaker: '石田龙弦', text: '北边的地狱——所有灵魂的终点。地狱之门在等你。' },
      ]},
      { x: 0.8, y: 0.65, id: 'npc_s28', role: 'lore', dialogue: [
        { speaker: '雨龙', text: '圣文字的力量源于灵魂深处。完成后，去地狱——那是所有灵魂的终点。' },
        { speaker: '雨龙', text: '地狱之门的钥匙在你手中。斩魄刀、虚化、完现术、圣文字——四力合一，门就会开。' },
      ]},

    ],
    enemies: [

      { name: 'm_stern_cap', type: '恶妖', element: '无', x: 0.7, y: 0.75 },
      { name: 'm_soldat_elite', type: '恶妖', element: '无', x: 0.7, y: 0.24 },
      { name: 'm_guard', type: '恶妖', element: '无', x: 0.08, y: 0.15 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.16, y: 0.6 },
      { name: 'm_stern', type: '恶妖', element: '无', x: 0.4, y: 0.5 },
      // ── 区域Boss（哈斯沃德） ──
      { name: 'b_haschwalth', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.06, y: 0.09 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.48, y: 0.36 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.95, y: 0.65 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.29, y: 0.08 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.73, y: 0.35 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.05, y: 0.9 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.49, y: 0.1 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.93, y: 0.36 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.26, y: 0.91 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.75, y: 0.08 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.07, y: 0.64 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.49, y: 0.92 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.28, y: 0.65 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.72, y: 0.9 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.05, y: 0.39 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.47, y: 0.61 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.29, y: 0.33 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.7, y: 0.63 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.53, y: 0.38 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.95, y: 0.64 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.26, y: 0.09 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.72, y: 0.38 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.05, y: 0.91 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.48, y: 0.08 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.95, y: 0.37 },
      { name: 'm_visard2', type: '杂妖', element: '无', x: 0.3, y: 0.91 },
      { name: 'm_soldat_elite', type: '恶妖', element: '无', x: 0.7, y: 0.11 },
      { name: 'm_guard', type: '恶妖', element: '无', x: 0.05, y: 0.63 },
      { name: 'm_stern', type: '恶妖', element: '无', x: 0.52, y: 0.92 },
      { name: 'm_stern_cap', type: '恶妖', element: '无', x: 0.93, y: 0.1 },
      { name: 'm_soldat_elite', type: '恶妖', element: '无', x: 0.28, y: 0.62 },
      { name: 'm_guard', type: '恶妖', element: '无', x: 0.74, y: 0.92 },
      { name: 'm_stern', type: '恶妖', element: '无', x: 0.07, y: 0.33 },
      { name: 'm_stern_cap', type: '恶妖', element: '无', x: 0.52, y: 0.65 },
      { name: 'm_soldat_elite', type: '恶妖', element: '无', x: 0.95, y: 0.92 },
      { name: 'm_guard', type: '恶妖', element: '无', x: 0.25, y: 0.39 },
      { name: 'm_stern', type: '恶妖', element: '无', x: 0.72, y: 0.64 },
    ],
    gathering: [
      { x: 0.35, y: 0.87, type: '灵脉' },
      { x: 0.59, y: 0.87, type: '灵脉' },
      { x: 0.12, y: 0.34, type: '矿脉' },
      { x: 0.12, y: 0.05, type: '灵脉' },
      { x: 0.86, y: 0.26, type: '矿脉' },
      { x: 0.33, y: 0.75, type: '灵脉' },
      { x: 0.41, y: 0.32, type: '灵脉' },
      { x: 0.51, y: 0.23, type: '药草' },
      { x: 0.05, y: 0.11, type: '灵脉' },
      { x: 0.51, y: 0.34, type: '灵脉' },
      { x: 0.95, y: 0.65, type: '矿脉' },
      { x: 0.28, y: 0.08, type: '灵脉' },
      { x: 0.75, y: 0.38, type: '矿脉' },
      { x: 0.05, y: 0.92, type: '灵脉' },
      { x: 0.5, y: 0.1, type: '灵脉' },
      { x: 0.95, y: 0.34, type: '药草' },
      { x: 0.27, y: 0.91, type: '灵脉' },
      { x: 0.71, y: 0.08, type: '灵脉' },
      { x: 0.05, y: 0.62, type: '矿脉' },
      { x: 0.48, y: 0.92, type: '灵脉' },
      { x: 0.93, y: 0.08, type: '矿脉' },
      { x: 0.29, y: 0.64, type: '灵脉' },
      { x: 0.75, y: 0.92, type: '灵脉' },
      { x: 0.06, y: 0.35, type: '药草' },
      { x: 0.5, y: 0.65, type: '灵脉' },
      { x: 0.94, y: 0.92, type: '灵脉' },
      { x: 0.3, y: 0.39, type: '矿脉' },
      { x: 0.73, y: 0.65, type: '灵脉' },
      { x: 0.05, y: 0.11, type: '矿脉' },
      { x: 0.48, y: 0.37, type: '灵脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 17, targetX: 0.9, targetY: 0.5 },
      { edge: 'north', x: 0.5, y: 0.03, targetZone: 19, targetX: 0.5, targetY: 0.95 },
    ],
  };
