// Region 11 — 黑腔深部
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone11: ZoneConfig = {
    id: 11, name: '黑腔深部',
    backgroundImage: 'bg_zone_11',
    backgroundMode: 'cover',
    groundColor: 0x777788,
    npcs: [
      { x: 0.45, y: 0.35, id: 'npc_m11', role: 'merchant', dialogue: [
        { text: '黑腔深部的装备——用破面的灵压锻造。比白砂原的强多了。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(6, '黑腔', ['garganta_hat', 'garganta_armor', 'garganta_bracer', 'garganta_boots', 'garganta_belt', 'garganta_ring', 'garganta_necklace', 'garganta_charm', 'garganta_pendant']) },
      { x: 0.7, y: 0.5, id: 'npc_q09', role: 'quest', dialogue: [
        { text: '虚化的第二阶段试炼。在黑腔深处感受虚的灵压——然后掌控它！', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, id: 'sys_portal_hueco', role: 'return_point', dialogue: [
        { text: '黑腔深部的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', role: 'craft', dialogue: [
        { text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.6, y: 0.7, id: 'sys_board', role: 'quest_board', dialogue: [
        { text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f11', role: 'enhance', dialogue: [{ text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, id: 'npc_s37', role: 'side_quest', dialogue: [
        { text: '……虚……帮我……击败……破面……。' },
      ]},
      { x: 0.65, y: 0.8, id: 'npc_s33', role: 'side_quest', dialogue: [
        { text: '恐惧……你也能感受到吗？帮我收集灵脉，我教你对抗恐惧。' },
      ]},
      { x: 0.15, y: 0.5, id: 'npc_s27', role: 'lore', dialogue: [
        { text: '虚化不是力量——是代价。你的灵魂会被虚侵蚀。' },
        { text: '东边的虚夜宫——蓝染在那里等着。他的目的……无人知晓。' },
      ]},
      { x: 0.8, y: 0.65, id: 'npc_m12', role: 'lore', dialogue: [
        { text: '牺牲与守护——虚化的真谛不是毁灭，而是为了守护而化身猛兽。' },
        { text: '虚夜宫在东边。蓝染的野心……最终会毁灭一切。' },
      ]},

    ],
    enemies: [

      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.28, y: 0.24 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.45, y: 0.45 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.7, y: 0.47 },
      { name: 'm_frac_mid', type: '恶妖', element: '无', x: 0.27, y: 0.5 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.8, y: 0.7 },
      // ── 区域Boss（乌尔奇奥拉） ──
      { name: 'b_ulquiorra', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.06, y: 0.11 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.48, y: 0.37 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.93, y: 0.67 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.26, y: 0.1 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.71, y: 0.36 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.48, y: 0.08 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.94, y: 0.38 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.29, y: 0.92 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.74, y: 0.11 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.05, y: 0.61 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.52, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.27, y: 0.63 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.72, y: 0.92 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.05, y: 0.36 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.53, y: 0.66 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.93, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.27, y: 0.33 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.71, y: 0.62 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.06, y: 0.09 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.52, y: 0.37 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.92, y: 0.61 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.3, y: 0.08 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.75, y: 0.38 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.06, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.53, y: 0.08 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.95, y: 0.38 },
      { name: 'm_frac_mid', type: '恶妖', element: '无', x: 0.26, y: 0.92 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.75, y: 0.11 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.05, y: 0.67 },
      { name: 'm_frac_mid', type: '恶妖', element: '无', x: 0.47, y: 0.89 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.94, y: 0.08 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.29, y: 0.66 },
      { name: 'm_frac_mid', type: '恶妖', element: '无', x: 0.71, y: 0.92 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.05, y: 0.37 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.48, y: 0.64 },
    ],
    gathering: [
      { x: 0.38, y: 0.55, type: '矿脉' },
      { x: 0.33, y: 0.65, type: '药草' },
      { x: 0.19, y: 0.52, type: '药草' },
      { x: 0.12, y: 0.2, type: '药草' },
      { x: 0.79, y: 0.9, type: '药草' },
      { x: 0.65, y: 0.86, type: '灵脉' },
      { x: 0.57, y: 0.08, type: '灵脉' },
      { x: 0.9, y: 0.3, type: '灵木' },
      { x: 0.05, y: 0.08, type: '矿脉' },
      { x: 0.48, y: 0.38, type: '药草' },
      { x: 0.95, y: 0.62, type: '药草' },
      { x: 0.25, y: 0.09, type: '药草' },
      { x: 0.71, y: 0.36, type: '药草' },
      { x: 0.05, y: 0.91, type: '灵脉' },
      { x: 0.48, y: 0.11, type: '灵脉' },
      { x: 0.95, y: 0.37, type: '灵木' },
      { x: 0.25, y: 0.92, type: '矿脉' },
      { x: 0.7, y: 0.08, type: '药草' },
      { x: 0.05, y: 0.64, type: '药草' },
      { x: 0.52, y: 0.92, type: '药草' },
      { x: 0.95, y: 0.08, type: '药草' },
      { x: 0.26, y: 0.62, type: '灵脉' },
      { x: 0.71, y: 0.92, type: '灵脉' },
      { x: 0.05, y: 0.33, type: '灵木' },
      { x: 0.48, y: 0.64, type: '矿脉' },
      { x: 0.93, y: 0.91, type: '药草' },
      { x: 0.27, y: 0.37, type: '药草' },
      { x: 0.7, y: 0.64, type: '药草' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 10, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 12, targetX: 0.08, targetY: 0.5 },
    ],
  };
