// Region 16 — 影之领域
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone16: ZoneConfig = {
    id: 16, name: '影之领域',
    backgroundImage: 'bg_zone_16',
    backgroundMode: 'cover',
    groundColor: 0x334455,
    npcs: [
      { x: 0.45, y: 0.3, name: '哈斯沃德', role: 'merchant', dialogue: [
        { speaker: '哈斯沃德', text: '无形帝国的装备，以灭却师之力锻造。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(8, '星十字', ['flame_hat', 'flame_armor', 'flame_bracer', 'flame_boots', 'flame_belt', 'ruby_ring', 'flame_heart_necklace', 'flame_charm', 'flame_pendant']) },
      { x: 0.2, y: 0.65, name: '巴兹比', role: 'quest', dialogue: [
        { speaker: '巴兹比', text: '你身上流着死神的血。但圣文字也能为你所用——想试试吗？', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.1, y: 0.25, name: '影之领域', role: 'return_point', dialogue: [
        { speaker: '影之领域', text: '灭却师的影之通道。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '影之铁匠', role: 'enhance', dialogue: [{ speaker: '影之铁匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.85, y: 0.85, name: '艾斯·诺特', role: 'side_quest', dialogue: [
        { speaker: '艾斯·诺特', text: '恐惧……让我看看你能收集多少灵脉来对抗我的恐惧。' },
      ]},
      { x: 0.4, y: 0.7, name: '邦比爱塔', role: 'side_quest', dialogue: [
        { speaker: '邦比爱塔', text: '无聊死了！帮我炸几只圣兵练练手！' },
      ]},
      { x: 0.75, y: 0.5, name: '友哈巴赫(残影)', role: 'lore', dialogue: [
        { speaker: '友哈巴赫(残影)', text: '全知全能。这就是我的圣文字"A"的力量。你配拥有什么字母？' },
        { speaker: '友哈巴赫(残影)', text: '东边的星十字宫——灭却师的圣域。那里有更强大的骑士在等你。' },
      ]},
      { x: 0.25, y: 0.15, name: '石田龙弦', role: 'lore', dialogue: [
        { speaker: '石田龙弦', text: '圣文字是每个灭却师体内刻印的字母。代表他们独特的能力。' },
        { speaker: '石田龙弦', text: '银架城在更东边。友哈巴赫的王座在那里。但地狱……那是最深的秘密。' },
      ]},
    ],
    enemies: [

      { name: '圣兵', type: '杂妖', element: '无', x: 0.3, y: 0.2 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.6, y: 0.45 }, { name: '圣兵', type: '杂妖', element: '无', x: 1.2, y: 0.7 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 1.7, y: 0.3 }, { name: '虚化兵', type: '杂妖', element: '无', x: 2.2, y: 0.55 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 2.5, y: 0.25 }, { name: '虚化兵', type: '杂妖', element: '无', x: 0.2, y: 0.8 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 1.85, y: 0.75 }, { name: '圣兵', type: '杂妖', element: '无', x: 2.8, y: 0.6 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.5, y: 0.15 },
      // ── 区域Boss（村正） ──
      { name: '村正', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.5, y: 0.38 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.94, y: 0.66 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.26, y: 0.09 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.74, y: 0.35 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.06, y: 0.92 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.48, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.95, y: 0.34 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.27, y: 0.92 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.71, y: 0.08 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.05, y: 0.66 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.51, y: 0.92 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.95, y: 0.1 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.3, y: 0.61 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.74, y: 0.92 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.05, y: 0.37 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.51, y: 0.67 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.25, y: 0.34 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.72, y: 0.64 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.05, y: 0.09 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.47, y: 0.39 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.95, y: 0.66 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.3, y: 0.08 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.71, y: 0.38 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.05, y: 0.92 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.53, y: 0.09 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.94, y: 0.34 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.26, y: 0.9 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.71, y: 0.11 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.05, y: 0.61 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.5, y: 0.89 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.93, y: 0.1 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.3, y: 0.67 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.71, y: 0.92 },
    ],
    gathering: [
      { x: 0.1, y: 0.3, type: '矿脉' },
      { x: 0.3, y: 0.65, type: '灵木' },
      { x: 0.55, y: 0.25, type: '药草' },
      { x: 0.8, y: 0.55, type: '矿脉' },
      { x: 1.1, y: 0.7, type: '灵木' },
      { x: 1.4, y: 0.35, type: '药草' },
      { x: 1.7, y: 0.15, type: '矿脉' },
      { x: 2, y: 0.65, type: '灵木' },
      { x: 2.3, y: 0.45, type: '药草' },
      { x: 2.6, y: 0.8, type: '矿脉' },
      { x: 0.45, y: 0.55, type: '灵脉' },
      { x: 2.1, y: 0.2, type: '灵脉' },
      { x: 0.07, y: 0.11, type: '矿脉' },
      { x: 0.52, y: 0.39, type: '灵木' },
      { x: 0.95, y: 0.66, type: '药草' },
      { x: 0.25, y: 0.08, type: '矿脉' },
      { x: 0.73, y: 0.35, type: '灵木' },
      { x: 0.05, y: 0.92, type: '药草' },
      { x: 0.53, y: 0.08, type: '矿脉' },
      { x: 0.95, y: 0.39, type: '灵木' },
      { x: 0.26, y: 0.92, type: '药草' },
      { x: 0.71, y: 0.1, type: '矿脉' },
      { x: 0.06, y: 0.63, type: '灵脉' },
      { x: 0.52, y: 0.89, type: '灵脉' },
      { x: 0.95, y: 0.08, type: '矿脉' },
      { x: 0.3, y: 0.63, type: '灵木' },
      { x: 0.71, y: 0.92, type: '药草' },
      { x: 0.07, y: 0.36, type: '矿脉' },
      { x: 0.52, y: 0.67, type: '灵木' },
      { x: 0.95, y: 0.9, type: '药草' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 15, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 17, targetX: 0.08, targetY: 0.5 },
    ],
  };
