// Region 10 — 白砂原
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone10: ZoneConfig = {
    id: 10, name: '白砂原',
    backgroundImage: 'bg_zone_10',
    backgroundMode: 'cover',
    groundColor: 0x888899,
    npcs: [
      { x: 0.4, y: 0.3, id: 'npc_m10', role: 'merchant', dialogue: [
        { speaker: '远行商', text: '虚圈的装备很特别！都是用虚壳做的！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(5, '虚壳', ['stud_hat', 'stud_armor', 'stud_bracer', 'stud_boots', 'stud_belt', 'jade_ring', 'mist_necklace', 'mist_charm', 'swamp_pendant']) },
      { x: 0.7, y: 0.5, id: 'npc_q08', role: 'quest', dialogue: [
        { speaker: '残影·冥', text: '你为了力量来到虚圈。让我看看——你是否值得拥有虚化。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.2, id: 'sys_portal_hueco', name: '黑腔', role: 'return_point', dialogue: [
        { speaker: '黑腔', text: '连接虚圈与现世的裂缝。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.75, y: 0.5, id: 'sys_board', name: '任务公告板', role: 'quest_board', dialogue: [
        { speaker: '任务公告板', text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f10', role: 'enhance', dialogue: [{ speaker: '砂原锻', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.3, y: 0.45, id: 'npc_s26', role: 'side_quest', dialogue: [
        { speaker: '密牙', text: '喂！最强破面在此！帮我对付几只亚丘卡斯练练手。' },
      ]},
      { x: 0.65, y: 0.8, id: 'npc_q09', role: 'side_quest', dialogue: [
        { speaker: '朱华', text: '我的触手被虚群缠住了……帮我清理它们，我告诉你虚化的秘密。' },
      ]},
      { x: 0.2, y: 0.65, id: 'npc_q10', role: 'lore', dialogue: [
        { speaker: '残影·牙', text: '虚化——那是将虚的力量融入死神之体的禁忌之术。你准备好了吗？' },
        { speaker: '残影·牙', text: '东边的黑腔深部——更强大的破面在那里。虚夜宫在更深处。' },
      ]},
      { x: 0.55, y: 0.6, id: 'npc_s27', role: 'lore', dialogue: [
        { speaker: '星塔', text: '力量越大，孤独越深。虚化会改变你——不只是力量，还有灵魂。' },
        { speaker: '星塔', text: '虚夜宫的蓝染……他是这一切的幕后黑手。但你现在还见不到他。' },
      ]},

    ],
    enemies: [

      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.3, y: 0.2 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.7, y: 0.35 }, { name: 'm_frac_low', type: '杂妖', element: '无', x: 1.2, y: 0.6 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 1.8, y: 0.25 }, { name: 'm_adjuchas', type: '恶妖', element: '无', x: 2.2, y: 0.55 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 2.6, y: 0.7 }, { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.4, y: 0.7 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 1.5, y: 0.15 }, { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.1, y: 0.5 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 2.85, y: 0.35 },
      // ── 区域Boss（葛力姆乔） ──
      { name: 'b_grimmjow', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.5, y: 0.35 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.92, y: 0.64 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.26, y: 0.11 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.75, y: 0.34 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.47, y: 0.08 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.92, y: 0.37 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.27, y: 0.9 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.75, y: 0.09 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.05, y: 0.65 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.51, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.95, y: 0.1 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.25, y: 0.65 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.71, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.08, y: 0.37 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.52, y: 0.63 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.93, y: 0.92 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.25, y: 0.37 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.74, y: 0.66 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.07, y: 0.08 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.51, y: 0.37 },
      { name: 'm_frac_low', type: '杂妖', element: '无', x: 0.95, y: 0.64 },
      { name: 'm_gillian_swarm', type: '杂妖', element: '无', x: 0.26, y: 0.09 },
      { name: 'm_gillian2', type: '杂妖', element: '无', x: 0.72, y: 0.38 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.05, y: 0.92 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.52, y: 0.09 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.95, y: 0.34 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.26, y: 0.92 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.7, y: 0.08 },
      { name: 'm_adjuchas', type: '恶妖', element: '无', x: 0.06, y: 0.64 },
      { name: 'm_frac_high', type: '恶妖', element: '无', x: 0.5, y: 0.91 },
    ],
    gathering: [
      { x: 0.1, y: 0.2, type: '矿脉' },
      { x: 0.3, y: 0.55, type: '灵木' },
      { x: 0.55, y: 0.15, type: '药草' },
      { x: 0.75, y: 0.7, type: '矿脉' },
      { x: 0.95, y: 0.35, type: '灵木' },
      { x: 1.2, y: 0.8, type: '药草' },
      { x: 1.5, y: 0.4, type: '矿脉' },
      { x: 1.8, y: 0.65, type: '灵木' },
      { x: 2.1, y: 0.2, type: '药草' },
      { x: 2.5, y: 0.5, type: '矿脉' },
      { x: 0.6, y: 0.45, type: '灵脉' },
      { x: 2.3, y: 0.85, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '矿脉' },
      { x: 0.53, y: 0.38, type: '灵木' },
      { x: 0.95, y: 0.67, type: '药草' },
      { x: 0.28, y: 0.08, type: '矿脉' },
      { x: 0.74, y: 0.35, type: '灵木' },
      { x: 0.06, y: 0.92, type: '药草' },
      { x: 0.47, y: 0.09, type: '矿脉' },
      { x: 0.95, y: 0.34, type: '灵木' },
      { x: 0.25, y: 0.92, type: '药草' },
      { x: 0.72, y: 0.08, type: '矿脉' },
      { x: 0.05, y: 0.63, type: '灵脉' },
      { x: 0.52, y: 0.92, type: '灵脉' },
      { x: 0.95, y: 0.1, type: '矿脉' },
      { x: 0.3, y: 0.63, type: '灵木' },
      { x: 0.74, y: 0.92, type: '药草' },
      { x: 0.07, y: 0.35, type: '矿脉' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 9, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 11, targetX: 0.08, targetY: 0.5 },
    ],
  };
