// Region 17 — 星十字宫
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone17: ZoneConfig = {
    id: 17, name: '星十字宫',
    groundColor: 0x334466, roadColor: 0x556688, treeColor: 0x223355,
    decorations: [
      { type: 'house', x: 0.3, y: 0.35, w: 180, h: 130 },
      { type: 'house', x: 0.6, y: 0.55, w: 160, h: 120 },
      { type: 'pond', x: 0.45, y: 0.2, w: 90, h: 65 },
    ],
    npcs: [
      { x: 0.45, y: 0.35, name: '莉托托', role: 'merchant', dialogue: [
        { speaker: '莉托托', text: '饿了……买装备顺便给我带点吃的？星十字宫的货可是最好的。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(9, '星十字', ['star_hat', 'star_armor', 'star_bracer', 'star_boots', 'star_belt', 'star_ring', 'star_necklace', 'star_charm', 'star_pendant']) },
      { x: 0.7, y: 0.5, name: '邦比爱塔', role: 'quest', dialogue: [
        { speaker: '邦比爱塔', text: '圣文字的第二阶段试炼——在星十字宫释放你的字母！', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '影之领域', role: 'return_point', dialogue: [
        { speaker: '影之领域', text: '星十字宫的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '星十字工匠', role: 'enhance', dialogue: [{ speaker: '星十字工匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '艾斯·诺特', role: 'side_quest', dialogue: [
        { speaker: '艾斯·诺特', text: '恐惧的力量需要灵脉支撑。帮我采集，我让你体验真正的恐惧。' },
      ]},
      { x: 0.65, y: 0.8, name: '杰拉德', role: 'side_quest', dialogue: [
        { speaker: '杰拉德', text: '奇迹需要牺牲。帮我击败几只虚化兵，奇迹就会降临。' },
      ]},
      { x: 0.15, y: 0.5, name: '哈斯沃德', role: 'lore', dialogue: [
        { speaker: '哈斯沃德', text: '我的圣文字"B"——均衡。与世界为敌的人，必须被均衡。' },
        { speaker: '哈斯沃德', text: '东边的银架城——友哈巴赫大人的王座。最终试炼在那里。' },
      ]},
      { x: 0.8, y: 0.65, name: '石田雨龙', role: 'lore', dialogue: [
        { speaker: '石田雨龙', text: '友哈巴赫选我作为他的继任者……但这只是他的棋局。' },
        { speaker: '石田雨龙', text: '银架城在东边。那里有地狱之门的线索——友哈巴赫的终极目标。' },
      ]},
    ],
    enemies: [

      { name: '圣兵', type: '杂妖', element: '无', x: 0.78, y: 0.7 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.49, y: 0.5 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.9, y: 0.62 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.1, y: 0.56 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.3, y: 0.2 },
      // ── 区域Boss（巴兹比） ──
      { name: '巴兹比', type: '妖王', element: '火', x: 0.93, y: 0.88, isBoss: true },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.06, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.49, y: 0.35 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.94, y: 0.67 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.28, y: 0.08 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.71, y: 0.36 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.08, y: 0.92 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.51, y: 0.1 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.93, y: 0.36 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.27, y: 0.92 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.72, y: 0.08 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.08, y: 0.64 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.5, y: 0.91 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.94, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.3, y: 0.65 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.72, y: 0.9 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.05, y: 0.36 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.52, y: 0.63 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.95, y: 0.91 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.29, y: 0.36 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.71, y: 0.63 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.06, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.48, y: 0.34 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.95, y: 0.67 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.28, y: 0.08 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.7, y: 0.37 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.06, y: 0.92 },
      { name: '圣兵', type: '杂妖', element: '无', x: 0.51, y: 0.08 },
      { name: '虚化兵', type: '杂妖', element: '无', x: 0.95, y: 0.33 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.29, y: 0.91 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.74, y: 0.08 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.05, y: 0.61 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.47, y: 0.92 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.93, y: 0.1 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.29, y: 0.66 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.74, y: 0.9 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.06, y: 0.37 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.47, y: 0.64 },
      { name: '圣兵精英', type: '恶妖', element: '无', x: 0.93, y: 0.92 },
      { name: '星十字骑士·长', type: '恶妖', element: '无', x: 0.29, y: 0.35 },
      { name: '星十字骑士', type: '恶妖', element: '无', x: 0.75, y: 0.66 },
    ],
    gathering: [
      { x: 0.88, y: 0.52, type: '灵脉' },
      { x: 0.13, y: 0.24, type: '矿脉' },
      { x: 0.3, y: 0.74, type: '灵木' },
      { x: 0.35, y: 0.82, type: '灵木' },
      { x: 0.8, y: 0.81, type: '药草' },
      { x: 0.36, y: 0.16, type: '矿脉' },
      { x: 0.8, y: 0.75, type: '矿脉' },
      { x: 0.37, y: 0.79, type: '药草' },
      { x: 0.05, y: 0.08, type: '灵脉' },
      { x: 0.5, y: 0.34, type: '矿脉' },
      { x: 0.95, y: 0.64, type: '灵木' },
      { x: 0.28, y: 0.08, type: '灵木' },
      { x: 0.72, y: 0.34, type: '药草' },
      { x: 0.07, y: 0.91, type: '矿脉' },
      { x: 0.48, y: 0.1, type: '矿脉' },
      { x: 0.93, y: 0.35, type: '药草' },
      { x: 0.27, y: 0.89, type: '灵脉' },
      { x: 0.72, y: 0.08, type: '矿脉' },
      { x: 0.07, y: 0.65, type: '灵木' },
      { x: 0.49, y: 0.92, type: '灵木' },
      { x: 0.94, y: 0.11, type: '药草' },
      { x: 0.27, y: 0.61, type: '矿脉' },
      { x: 0.71, y: 0.92, type: '矿脉' },
      { x: 0.08, y: 0.34, type: '药草' },
      { x: 0.52, y: 0.65, type: '灵脉' },
      { x: 0.95, y: 0.92, type: '矿脉' },
      { x: 0.28, y: 0.35, type: '灵木' },
      { x: 0.72, y: 0.64, type: '灵木' },
      { x: 0.06, y: 0.09, type: '药草' },
      { x: 0.48, y: 0.39, type: '矿脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 16, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 18, targetX: 0.08, targetY: 0.5 },
    ],
  };
