// Region 15 — 完现术总本山
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone15: ZoneConfig = {
    id: 15, name: '完现术总本山',
    backgroundImage: 'bg_zone_15',
    backgroundMode: 'cover',
    groundColor: 0x553366,
    npcs: [
      { x: 0.45, y: 0.35, name: '银城空吾', role: 'merchant', dialogue: [
        { speaker: '银城空吾', text: '完现术总本山——所有完现术者的圣地。这里的装备是最高级的。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(8, '完现', ['fullbring_hat', 'fullbring_armor', 'fullbring_bracer', 'fullbring_boots', 'fullbring_belt', 'fullbring_ring', 'fullbring_necklace', 'fullbring_charm', 'fullbring_pendant']) },
      { x: 0.7, y: 0.5, name: '月岛秀九郎(残影)', role: 'quest', dialogue: [
        { speaker: '月岛秀九郎(残影)', text: '完现术的最终试炼——用你的灵魂改写现实。打败我，你就毕业了。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '完现术总本山的传送门。北边通往无形帝国。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '完现术锻造师', role: 'enhance', dialogue: [{ speaker: '完现术锻造师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '茶渡泰虎', role: 'side_quest', dialogue: [
        { speaker: '茶渡泰虎', text: '我的右臂力量还不稳定……帮我采集灵木来调整。' },
      ]},
      { x: 0.65, y: 0.8, name: '井上织姬(残影)', role: 'side_quest', dialogue: [
        { speaker: '井上织姬(残影)', text: '双天归盾需要灵脉的能量。帮我采集，我为你强化护盾。' },
      ]},
      { x: 0.15, y: 0.5, name: '浦原喜助', role: 'lore', dialogue: [
        { speaker: '浦原喜助', text: '你又回来了？完现术之后是灭却师……真是有趣的研究对象。' },
        { speaker: '浦原喜助', text: '无形帝国的门在北边。做好准备再去——那里的敌人不是虚，是灭却师。' },
      ]},
      { x: 0.8, y: 0.65, name: '石田雨龙', role: 'lore', dialogue: [
        { speaker: '石田雨龙', text: '灭却师……我的父亲说过，圣文字是灵魂深处的刻印。' },
        { speaker: '石田雨龙', text: '北边的影之领域——无形帝国的入口。友哈巴赫在那里等着。' },
      ]},
    ],
    enemies: [

      { name: '完现者·精英', type: '恶妖', element: '无', x: 0.18, y: 0.39 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.66, y: 0.54 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.91, y: 0.72 },
      { name: '完现术·暴走', type: '恶妖', element: '无', x: 0.44, y: 0.52 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.3, y: 0.7 },
      // ── 区域Boss（月岛秀九郎） ──
      { name: '月岛秀九郎', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.1 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.48, y: 0.34 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.94, y: 0.64 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.28, y: 0.1 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.37 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.07, y: 0.91 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.49, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.37 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.28, y: 0.92 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.74, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.07, y: 0.64 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.49, y: 0.91 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.28, y: 0.62 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.75, y: 0.9 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.08, y: 0.36 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.49, y: 0.62 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.89 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.27, y: 0.38 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.63 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.1 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.53, y: 0.34 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.65 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.25, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.75, y: 0.39 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.51, y: 0.09 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.93, y: 0.34 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.3, y: 0.92 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.7, y: 0.09 },
      { name: '完现术·暴走', type: '恶妖', element: '无', x: 0.05, y: 0.65 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.51, y: 0.92 },
      { name: '完现者·精英', type: '恶妖', element: '无', x: 0.95, y: 0.08 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.25, y: 0.64 },
      { name: '完现术·暴走', type: '恶妖', element: '无', x: 0.7, y: 0.92 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.05, y: 0.36 },
      { name: '完现者·精英', type: '恶妖', element: '无', x: 0.48, y: 0.67 },
    ],
    gathering: [
      { x: 0.47, y: 0.93, type: '灵脉' },
      { x: 0.33, y: 0.42, type: '灵脉' },
      { x: 0.71, y: 0.52, type: '矿脉' },
      { x: 0.2, y: 0.32, type: '灵脉' },
      { x: 0.83, y: 0.07, type: '灵木' },
      { x: 0.73, y: 0.89, type: '灵脉' },
      { x: 0.83, y: 0.23, type: '灵脉' },
      { x: 0.42, y: 0.07, type: '矿脉' },
      { x: 0.07, y: 0.1, type: '灵脉' },
      { x: 0.49, y: 0.39, type: '灵脉' },
      { x: 0.95, y: 0.66, type: '矿脉' },
      { x: 0.28, y: 0.08, type: '灵脉' },
      { x: 0.74, y: 0.38, type: '灵木' },
      { x: 0.05, y: 0.92, type: '灵脉' },
      { x: 0.48, y: 0.08, type: '灵脉' },
      { x: 0.95, y: 0.33, type: '矿脉' },
      { x: 0.27, y: 0.9, type: '灵脉' },
      { x: 0.74, y: 0.11, type: '灵脉' },
      { x: 0.07, y: 0.65, type: '矿脉' },
      { x: 0.52, y: 0.92, type: '灵脉' },
      { x: 0.95, y: 0.08, type: '灵木' },
      { x: 0.27, y: 0.62, type: '灵脉' },
      { x: 0.74, y: 0.91, type: '灵脉' },
      { x: 0.07, y: 0.39, type: '矿脉' },
      { x: 0.49, y: 0.66, type: '灵脉' },
      { x: 0.92, y: 0.92, type: '灵脉' },
      { x: 0.27, y: 0.38, type: '矿脉' },
      { x: 0.7, y: 0.65, type: '灵脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 14, targetX: 0.9, targetY: 0.5 },
      { edge: 'north', x: 0.5, y: 0.03, targetZone: 16, targetX: 0.5, targetY: 0.95 },
    ],
  };
