// Region 20 — 无间
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone20: ZoneConfig = {
    id: 20, name: '无间',
    groundColor: 0x2a1118, roadColor: 0x442230, treeColor: 0x1a0810,
    decorations: [
      { type: 'pond', x: 0.3, y: 0.3, w: 140, h: 100 },
      { type: 'house', x: 0.6, y: 0.55, w: 110, h: 80 },
      { type: 'pond', x: 0.45, y: 0.2, w: 85, h: 60 },
    ],
    npcs: [
      { x: 0.45, y: 0.35, name: '地狱狱卒', role: 'merchant', dialogue: [
        { speaker: '地狱狱卒', text: '无间——地狱最深处。这里的装备连咎人都害怕。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(10, '无间', ['muken_hat', 'muken_armor', 'muken_bracer', 'muken_boots', 'muken_belt', 'muken_ring', 'muken_necklace', 'muken_charm', 'muken_pendant']) },
      { x: 0.7, y: 0.5, name: '守门人', role: 'quest', dialogue: [
        { speaker: '守门人', text: '狱解的第二阶段试炼——在无间的黑暗中释放你的狱炎。', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '地狱之门', role: 'return_point', dialogue: [
        { speaker: '地狱之门', text: '无间的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '无间炼器师', role: 'enhance', dialogue: [{ speaker: '无间炼器师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '被囚的灵魂', role: 'side_quest', dialogue: [
        { speaker: '被囚的灵魂', text: '无间的混沌兽太强了……帮我清理几只，我告诉你终焉之渊的秘密。' },
      ]},
      { x: 0.65, y: 0.8, name: '地狱看守', role: 'side_quest', dialogue: [
        { speaker: '地狱看守', text: '地狱犬的牙齿是上好的材料。帮我击败几只地狱犬。' },
      ]},
      { x: 0.15, y: 0.5, name: '朽木露琪亚(残影)', role: 'lore', dialogue: [
        { speaker: '朽木露琪亚(残影)', text: '无间……蓝染曾经被封印在这里。现在这里只剩下混沌。' },
        { speaker: '朽木露琪亚(残影)', text: '东边的终焉之渊——地狱的终点。最终的试炼在那里等着你。' },
      ]},
      { x: 0.8, y: 0.65, name: '黑崎一护(残影)', role: 'lore', dialogue: [
        { speaker: '黑崎一护(残影)', text: '你走到这里了……始解、卍解、虚化、完现术、圣文字、狱解。' },
        { speaker: '黑崎一护(残影)', text: '终焉之渊在东边。那里有所有灵魂的终点——终焉之兽。打败它，你就完成了试炼。' },
      ]},
    ],
    enemies: [

      { name: '咎人', type: '杂妖', element: '无', x: 0.12, y: 0.39 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.77, y: 0.84 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.66, y: 0.2 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.57, y: 0.37 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.3, y: 0.7 },
      // ── 区域Boss（朱莲） ──
      { name: '朱莲', type: '妖王', element: '火', x: 0.93, y: 0.88, isBoss: true },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.1 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.48, y: 0.34 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.93, y: 0.66 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.3, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.7, y: 0.36 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.08, y: 0.92 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.52, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.94, y: 0.35 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.28, y: 0.92 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.72, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.63 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.49, y: 0.92 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.94, y: 0.1 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.29, y: 0.63 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.71, y: 0.92 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.06, y: 0.38 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.51, y: 0.66 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.92, y: 0.9 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.28, y: 0.38 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.7, y: 0.63 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.1 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.47, y: 0.39 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.95, y: 0.61 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.27, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.75, y: 0.39 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.06, y: 0.9 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.47, y: 0.1 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.95, y: 0.38 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.27, y: 0.92 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.7, y: 0.08 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.07, y: 0.62 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.51, y: 0.92 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.93, y: 0.08 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.29, y: 0.67 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.74, y: 0.92 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.07, y: 0.36 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.49, y: 0.63 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.94, y: 0.89 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.26, y: 0.34 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.75, y: 0.62 },
    ],
    gathering: [
      { x: 0.21, y: 0.66, type: '矿脉' },
      { x: 0.36, y: 0.89, type: '药草' },
      { x: 0.16, y: 0.5, type: '药草' },
      { x: 0.24, y: 0.66, type: '矿脉' },
      { x: 0.28, y: 0.7, type: '灵木' },
      { x: 0.34, y: 0.63, type: '灵木' },
      { x: 0.69, y: 0.2, type: '灵脉' },
      { x: 0.62, y: 0.16, type: '药草' },
      { x: 0.05, y: 0.09, type: '矿脉' },
      { x: 0.49, y: 0.39, type: '药草' },
      { x: 0.95, y: 0.64, type: '药草' },
      { x: 0.3, y: 0.08, type: '矿脉' },
      { x: 0.71, y: 0.35, type: '灵木' },
      { x: 0.05, y: 0.9, type: '灵木' },
      { x: 0.49, y: 0.11, type: '灵脉' },
      { x: 0.95, y: 0.34, type: '药草' },
      { x: 0.3, y: 0.92, type: '矿脉' },
      { x: 0.71, y: 0.08, type: '药草' },
      { x: 0.06, y: 0.64, type: '药草' },
      { x: 0.48, y: 0.91, type: '矿脉' },
      { x: 0.95, y: 0.08, type: '灵木' },
      { x: 0.25, y: 0.61, type: '灵木' },
      { x: 0.75, y: 0.92, type: '灵脉' },
      { x: 0.06, y: 0.38, type: '药草' },
      { x: 0.49, y: 0.62, type: '矿脉' },
      { x: 0.95, y: 0.92, type: '药草' },
      { x: 0.3, y: 0.37, type: '药草' },
      { x: 0.7, y: 0.64, type: '矿脉' },
      { x: 0.05, y: 0.08, type: '灵木' },
      { x: 0.51, y: 0.33, type: '灵木' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 19, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 21, targetX: 0.08, targetY: 0.5 },
    ],
  };
