// Region 9 — 真央灵术院
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone09: ZoneConfig = {
    id: 9, name: '真央灵术院',
    groundColor: 0xaaaabb, roadColor: 0xccccdd, treeColor: 0x888899,
    decorations: [
      { type: 'house', x: 0.3, y: 0.35, w: 140, h: 100 },
      { type: 'house', x: 0.6, y: 0.55, w: 130, h: 90 },
      { type: 'pond', x: 0.45, y: 0.2, w: 90, h: 65 },
    ],
    npcs: [
      { x: 0.45, y: 0.35, name: '朽木露琪亚', role: 'merchant', dialogue: [
        { speaker: '朽木露琪亚', text: '灵术院的装备都是毕业生留下的。你也要毕业了吧？', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(5, '灵术院', ['academy_hat', 'academy_armor', 'academy_bracer', 'academy_boots', 'academy_belt', 'academy_ring', 'academy_necklace', 'academy_charm', 'academy_pendant']) },
      { x: 0.7, y: 0.5, name: '朽木白哉', role: 'quest', dialogue: [
        { speaker: '朽木白哉', text: '卍解的最终试炼。通过它，你就不再是学徒了。准备好了吗？', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '灵术院的传送门。北边通往虚圈。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '灵术院炼器师', role: 'enhance', dialogue: [{ speaker: '灵术院炼器师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '雏森桃', role: 'side_quest', dialogue: [
        { speaker: '雏森桃', text: '我的鬼道练习材料不够了。帮我采集药草和灵脉。' },
      ]},
      { x: 0.65, y: 0.8, name: '吉良井鹤', role: 'side_quest', dialogue: [
        { speaker: '吉良井鹤', text: '灵术院地下室有叛逆死神潜伏。帮我清理几只。' },
      ]},
      { x: 0.15, y: 0.5, name: '浦原喜助', role: 'lore', dialogue: [
        { speaker: '浦原喜助', text: '卍解完成了吗？很好。接下来——虚化。' },
        { speaker: '浦原喜助', text: '北边的穿界门通往虚圈。虚化就在那里觉醒。但虚化是禁忌之术……谨慎使用。' },
      ]},
      { x: 0.8, y: 0.65, name: '山本元柳斋', role: 'lore', dialogue: [
        { speaker: '山本元柳斋', text: '你已完成卍解。但前方的敌人——虚圈的破面——不是普通虚可比的。' },
        { speaker: '山本元柳斋', text: '虚化是唯一能对抗破面的力量。去虚圈吧。' },
      ]},
    ],
    enemies: [

      { name: '上级死神', type: '杂妖', element: '无', x: 0.26, y: 0.35 },
      { name: '叛逆死神·长', type: '恶妖', element: '无', x: 0.66, y: 0.25 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.58, y: 0.66 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.8, y: 0.25 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.3, y: 0.7 },
      // ── 区域Boss（虚·学鬼） ──
      { name: '虚·学鬼(原创)', type: '妖将', element: '火', x: 0.93, y: 0.88, isBoss: true },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.05, y: 0.09 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.52, y: 0.37 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.95, y: 0.66 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.28, y: 0.08 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.73, y: 0.37 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.48, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.34 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.26, y: 0.92 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.72, y: 0.11 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.05, y: 0.66 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.48, y: 0.92 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.94, y: 0.1 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.29, y: 0.63 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.74, y: 0.91 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.36 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.52, y: 0.63 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.89 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.3, y: 0.37 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.72, y: 0.61 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.05, y: 0.09 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.47, y: 0.34 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.95, y: 0.61 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.28, y: 0.08 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.7, y: 0.37 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.06, y: 0.92 },
      { name: '上级死神', type: '杂妖', element: '无', x: 0.53, y: 0.11 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.92, y: 0.35 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.3, y: 0.91 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.73, y: 0.08 },
      { name: '叛逆死神·长', type: '恶妖', element: '无', x: 0.05, y: 0.61 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.48, y: 0.92 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.95, y: 0.08 },
    ],
    gathering: [
      { x: 0.21, y: 0.54, type: '灵脉' },
      { x: 0.07, y: 0.92, type: '灵木' },
      { x: 0.23, y: 0.69, type: '灵脉' },
      { x: 0.47, y: 0.27, type: '药草' },
      { x: 0.49, y: 0.81, type: '灵脉' },
      { x: 0.22, y: 0.64, type: '药草' },
      { x: 0.25, y: 0.43, type: '矿脉' },
      { x: 0.33, y: 0.06, type: '灵脉' },
      { x: 0.07, y: 0.08, type: '灵脉' },
      { x: 0.49, y: 0.35, type: '灵木' },
      { x: 0.95, y: 0.63, type: '灵脉' },
      { x: 0.29, y: 0.11, type: '药草' },
      { x: 0.75, y: 0.34, type: '灵脉' },
      { x: 0.08, y: 0.89, type: '药草' },
      { x: 0.47, y: 0.08, type: '矿脉' },
      { x: 0.93, y: 0.38, type: '灵脉' },
      { x: 0.27, y: 0.92, type: '灵脉' },
      { x: 0.72, y: 0.09, type: '灵木' },
      { x: 0.05, y: 0.63, type: '灵脉' },
      { x: 0.5, y: 0.92, type: '药草' },
      { x: 0.95, y: 0.08, type: '灵脉' },
      { x: 0.28, y: 0.64, type: '药草' },
      { x: 0.75, y: 0.9, type: '矿脉' },
      { x: 0.07, y: 0.38, type: '灵脉' },
      { x: 0.49, y: 0.67, type: '灵脉' },
      { x: 0.92, y: 0.92, type: '灵木' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 8, targetX: 0.9, targetY: 0.5 },
      { edge: 'north', x: 0.5, y: 0.03, targetZone: 10, targetX: 0.5, targetY: 0.95 },
    ],
  };
