// Region 2 — 空座高校
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone02: ZoneConfig = {
    id: 2, name: '空座高校',
    backgroundImage: 'bg_zone_02',
    backgroundMode: 'cover',
    groundColor: 0x445577,
    npcs: [
      { x: 0.45, y: 0.35, name: '浅野启吾', role: 'merchant', dialogue: [
        { speaker: '浅野启吾', text: '嘿嘿，我从浦原大叔那里进了些货。虽然不太会用，但装备还是靠谱的！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(1, '校园', ['school_hat', 'school_armor', 'school_bracer', 'school_boots', 'school_belt', 'school_ring', 'school_necklace', 'school_charm', 'school_pendant']) },
      { x: 0.75, y: 0.5, name: '黑崎夏梨', role: 'quest', dialogue: [
        { speaker: '黑崎夏梨', text: '学校附近出现了奇怪的影子……你能帮忙调查一下吗？', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '学校后山的微型穿界门。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '校园修理匠', role: 'enhance', dialogue: [{ speaker: '校园修理匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '本匠千代乃', role: 'side_quest', dialogue: [
        { speaker: '本匠千代乃', text: '我的书包被虚叼走了！帮我抢回来……对付几只低级虚就行。' },
      ]},
      { x: 0.65, y: 0.8, name: '小岛水色', role: 'side_quest', dialogue: [
        { speaker: '小岛水色', text: '学校天台的灵木可以用来做护身符。帮我收集一些？' },
      ]},
      { x: 0.15, y: 0.5, name: '黑崎游子', role: 'lore', dialogue: [
        { speaker: '黑崎游子', text: '哥哥总是不在家……你是不是也像哥哥一样能看见幽灵？' },
        { speaker: '黑崎游子', text: '一护哥哥说他要去尸魂界修行。流魂街在西边很远的地方。' },
      ]},
      { x: 0.8, y: 0.65, name: '浅野启吾', role: 'lore', dialogue: [
        { speaker: '浅野启吾', text: '最近镇子上的灵压越来越强了。虚被吸引过来了。' },
        { speaker: '浅野启吾', text: '听说河川敷那边有更强的虚出没。小心点。' },
      ]},
    ],
    enemies: [

      { name: '低级虚', type: '杂妖', element: '无', x: 0.23, y: 0.71 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.46, y: 0.13 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.58, y: 0.55 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.51, y: 0.72 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.15, y: 0.3 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.8, y: 0.4 },
      // ── 区域Boss（酸蚀虚） ──
      { name: '酸蚀虚', type: '妖将', element: '火', x: 0.93, y: 0.88, isBoss: true },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.49, y: 0.33 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.93, y: 0.64 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.3, y: 0.11 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.75, y: 0.34 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.05, y: 0.91 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.52, y: 0.08 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.95, y: 0.37 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.27, y: 0.91 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.7, y: 0.08 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.06, y: 0.64 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.53, y: 0.92 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.27, y: 0.65 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.75, y: 0.9 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.05, y: 0.36 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.5, y: 0.61 },
      { name: '蛇虚', type: '杂妖', element: '土', x: 0.93, y: 0.92 },
      { name: '低级虚', type: '杂妖', element: '无', x: 0.26, y: 0.35 },
      { name: '飞虚', type: '杂妖', element: '风', x: 0.74, y: 0.65 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.05, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.49, y: 0.39 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.95, y: 0.64 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.28, y: 0.08 },
    ],
    gathering: [
      { x: 0.89, y: 0.49, type: '灵脉' },
      { x: 0.71, y: 0.79, type: '矿脉' },
      { x: 0.11, y: 0.61, type: '灵木' },
      { x: 0.63, y: 0.33, type: '灵木' },
      { x: 0.53, y: 0.78, type: '灵脉' },
      { x: 0.53, y: 0.11, type: '灵木' },
      { x: 0.8, y: 0.4, type: '药草' },
      { x: 0.3, y: 0.6, type: '药草' },
      { x: 0.08, y: 0.08, type: '灵脉' },
      { x: 0.48, y: 0.35, type: '矿脉' },
      { x: 0.95, y: 0.63, type: '灵木' },
      { x: 0.28, y: 0.1, type: '灵木' },
      { x: 0.73, y: 0.33, type: '灵脉' },
      { x: 0.07, y: 0.92, type: '灵木' },
      { x: 0.48, y: 0.08, type: '药草' },
      { x: 0.95, y: 0.39, type: '药草' },
      { x: 0.26, y: 0.91, type: '灵脉' },
      { x: 0.71, y: 0.08, type: '矿脉' },
      { x: 0.06, y: 0.63, type: '灵木' },
      { x: 0.52, y: 0.91, type: '灵木' },
      { x: 0.95, y: 0.08, type: '灵脉' },
      { x: 0.28, y: 0.67, type: '灵木' },
      { x: 0.73, y: 0.92, type: '药草' },
      { x: 0.05, y: 0.38, type: '药草' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 1, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 3, targetX: 0.08, targetY: 0.5 },
    ],
  };
