// Region 5 — 戌吊
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone05: ZoneConfig = {
    id: 5, name: '戌吊',
    backgroundImage: 'bg_zone_05',
    backgroundMode: 'cover',
    groundColor: 0x665555,
    npcs: [
      { x: 0.45, y: 0.35, id: 'npc_m05', role: 'merchant', dialogue: [
        { speaker: '岩户集', text: '姐姐让我看店。戌吊的装备比润林安还强一点，别小看！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(3, '戌吊', ['inata_hat', 'inata_armor', 'inata_bracer', 'inata_boots', 'inata_belt', 'inata_ring', 'inata_necklace', 'inata_charm', 'inata_pendant']) },
      { x: 0.7, y: 0.5, id: 'npc_q05', role: 'quest', dialogue: [
        { speaker: '霜行', text: '戌吊附近的虚越来越强了。帮我清理几只，我推荐你参加始解试炼。', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, id: 'sys_return', name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '戌吊的传送据点。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.6, y: 0.5, id: 'sys_board', name: '任务公告板', role: 'quest_board', dialogue: [
        { speaker: '任务公告板', text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f05', role: 'enhance', dialogue: [{ speaker: '戌吊工', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, id: 'npc_s17', role: 'side_quest', dialogue: [
        { speaker: '雀羽', text: '总队长山本元柳斋大人的斩魄刀——流刃若火，是炎系最强。帮我收集灵脉。' },
      ]},
      { x: 0.65, y: 0.8, id: 'npc_s18', role: 'side_quest', dialogue: [
        { speaker: '七弦', text: '八番队的文书工作……帮我击败几只暴走虚，我给你写推荐信。' },
      ]},
      { x: 0.15, y: 0.5, id: 'npc_s15', role: 'lore', dialogue: [
        { speaker: '浮云', text: '始解——斩魄刀的第一次解放。你需要找到刀的名字。' },
        { speaker: '浮云', text: '草鹿在东边。那里有更强大的死神在等待试炼者。' },
      ]},
      { x: 0.8, y: 0.65, id: 'npc_s19', role: 'lore', dialogue: [
        { speaker: '春涧', text: '花天狂骨——我的斩魄刀。始解后能将孩童的游戏化为现实。' },
        { speaker: '春涧', text: '静灵庭在北边。完成始解后就能进入——但先过了草鹿那关。' },
      ]},

    ],
    enemies: [

      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.18, y: 0.09 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.14, y: 0.45 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.64, y: 0.09 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.52, y: 0.68 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.8, y: 0.5 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.3, y: 0.8 },
      // ── 区域Boss（多尔多尼） ──
      { name: 'b_dordonii', type: '妖将', element: '土', x: 0.93, y: 0.88, isBoss: true },
      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.06, y: 0.08 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.51, y: 0.37 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.95, y: 0.62 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.27, y: 0.08 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.7, y: 0.36 },
      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.05, y: 0.92 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.49, y: 0.08 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.95, y: 0.35 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.27, y: 0.92 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.73, y: 0.08 },
      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.07, y: 0.65 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.51, y: 0.91 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.93, y: 0.08 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.27, y: 0.64 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.71, y: 0.92 },
      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.06, y: 0.35 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.49, y: 0.61 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.27, y: 0.37 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.72, y: 0.61 },
      { name: 'm_sl_brute', type: '杂妖', element: '土', x: 0.05, y: 0.09 },
      { name: 'm_berserk_void', type: '杂妖', element: '无', x: 0.53, y: 0.34 },
      { name: 'm_rebel_grunt', type: '杂妖', element: '无', x: 0.93, y: 0.67 },
      { name: 'm_sl_thug', type: '杂妖', element: '土', x: 0.25, y: 0.08 },
      { name: 'm_berserk_void2', type: '杂妖', element: '无', x: 0.75, y: 0.39 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.05, y: 0.9 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.47, y: 0.08 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.95, y: 0.37 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.3, y: 0.92 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.75, y: 0.08 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.05, y: 0.62 },
      { name: 'm_gillian', type: '恶妖', element: '无', x: 0.51, y: 0.92 },
    ],
    gathering: [
      { x: 0.21, y: 0.27, type: '灵脉' },
      { x: 0.93, y: 0.9, type: '矿脉' },
      { x: 0.61, y: 0.27, type: '药草' },
      { x: 0.3, y: 0.49, type: '灵脉' },
      { x: 0.94, y: 0.81, type: '灵木' },
      { x: 0.9, y: 0.27, type: '灵木' },
      { x: 0.51, y: 0.16, type: '灵木' },
      { x: 0.13, y: 0.5, type: '灵脉' },
      { x: 0.08, y: 0.1, type: '灵脉' },
      { x: 0.5, y: 0.36, type: '矿脉' },
      { x: 0.95, y: 0.66, type: '药草' },
      { x: 0.28, y: 0.09, type: '灵脉' },
      { x: 0.73, y: 0.35, type: '灵木' },
      { x: 0.07, y: 0.9, type: '灵木' },
      { x: 0.5, y: 0.11, type: '灵木' },
      { x: 0.95, y: 0.37, type: '灵脉' },
      { x: 0.3, y: 0.9, type: '灵脉' },
      { x: 0.72, y: 0.08, type: '矿脉' },
      { x: 0.05, y: 0.64, type: '药草' },
      { x: 0.48, y: 0.91, type: '灵脉' },
      { x: 0.95, y: 0.08, type: '灵木' },
      { x: 0.27, y: 0.66, type: '灵木' },
      { x: 0.74, y: 0.92, type: '灵木' },
      { x: 0.05, y: 0.35, type: '灵脉' },
      { x: 0.5, y: 0.65, type: '灵脉' },
      { x: 0.95, y: 0.89, type: '矿脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 4, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 6, targetX: 0.08, targetY: 0.5 },
    ],
  };
