// Region 21 — 终焉之渊
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone21: ZoneConfig = {
    id: 21, name: '终焉之渊',
    backgroundImage: 'bg_zone_21',
    backgroundMode: 'cover',
    groundColor: 0x1a0a10,
    npcs: [
      { x: 0.45, y: 0.35, name: '终焉看守', role: 'merchant', dialogue: [
        { speaker: '终焉看守', text: '终焉之渊——所有灵魂的终点。这里的装备是地狱最高级的。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(11, '终焉', ['final_hat', 'final_armor', 'final_bracer', 'final_boots', 'final_belt', 'final_ring', 'final_necklace', 'final_charm', 'final_pendant']) },
      { x: 0.7, y: 0.5, name: '朽木露琪亚(残影)', role: 'quest', dialogue: [
        { speaker: '朽木露琪亚(残影)', text: '最终试炼——终焉之兽。它是所有负面灵魂的集合体。打败它，完成你的使命。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '地狱之门', role: 'return_point', dialogue: [
        { speaker: '地狱之门', text: '终焉之渊的传送门——通往你已走过的所有世界。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……最后的制造阵法。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '终焉锻造师', role: 'enhance', dialogue: [{ speaker: '终焉锻造师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '地狱之王', role: 'side_quest', dialogue: [
        { speaker: '地狱之王', text: '你竟然走到了这里……帮我击败终焉之兽的爪牙，我给你地狱之王的宝物。' },
      ]},
      { x: 0.65, y: 0.8, name: '被囚的灵魂', role: 'side_quest', dialogue: [
        { speaker: '被囚的灵魂', text: '终焉之渊的灵脉是最后的力量源泉。帮我采集，我为你祝福。' },
      ]},
      { x: 0.15, y: 0.5, name: '黑崎一护(残影)', role: 'lore', dialogue: [
        { speaker: '黑崎一护(残影)', text: '你的旅途到这里就快结束了。始解、卍解、虚化、完现术、圣文字、狱解——六大力量体系。' },
        { speaker: '黑崎一护(残影)', text: '记住：力量不是为了毁灭，而是为了守护。这才是死神真正的意义。' },
      ]},
      { x: 0.8, y: 0.65, name: '浦原喜助', role: 'lore', dialogue: [
        { speaker: '浦原喜助', text: '哟，最后了啊。从浦原商店街到这里——你走了很远的路。' },
        { speaker: '浦原喜助', text: '终焉之兽在等着你。打败它——然后回来。我请你喝茶。' },
      ]},
    ],
    enemies: [

      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.42, y: 0.58 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.59, y: 0.26 },
      { name: '混沌兽·极', type: '恶妖', element: '无', x: 0.21, y: 0.33 },
      { name: '地狱之王', type: '恶妖', element: '无', x: 0.06, y: 0.94 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.7, y: 0.8 },
      // ── 区域Boss（蓝染惣右介） ──
      { name: '蓝染惣右介', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.08, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.53, y: 0.37 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.93, y: 0.64 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.1 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.74, y: 0.39 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.5, y: 0.1 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.95, y: 0.36 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.26, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.74, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.07, y: 0.66 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.48, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.94, y: 0.09 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.63 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.71, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.07, y: 0.35 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.49, y: 0.66 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.94, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.37 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.72, y: 0.67 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.48, y: 0.38 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.93, y: 0.63 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.11 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.75, y: 0.33 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.07, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.51, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.95, y: 0.36 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.9 },
      { name: '地狱之王', type: '恶妖', element: '无', x: 0.72, y: 0.08 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.05, y: 0.61 },
      { name: '混沌兽·极', type: '恶妖', element: '无', x: 0.53, y: 0.9 },
      { name: '地狱之王', type: '恶妖', element: '无', x: 0.95, y: 0.09 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.29, y: 0.65 },
      { name: '混沌兽·极', type: '恶妖', element: '无', x: 0.75, y: 0.92 },
      { name: '地狱之王', type: '恶妖', element: '无', x: 0.05, y: 0.34 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.5, y: 0.61 },
      { name: '混沌兽·极', type: '恶妖', element: '无', x: 0.92, y: 0.89 },
      { name: '地狱之王', type: '恶妖', element: '无', x: 0.26, y: 0.38 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.71, y: 0.61 },
    ],
    gathering: [
      { x: 0.49, y: 0.16, type: '药草' },
      { x: 0.82, y: 0.69, type: '灵木' },
      { x: 0.73, y: 0.32, type: '灵木' },
      { x: 0.78, y: 0.88, type: '矿脉' },
      { x: 0.07, y: 0.72, type: '药草' },
      { x: 0.71, y: 0.9, type: '灵木' },
      { x: 0.07, y: 0.62, type: '矿脉' },
      { x: 0.21, y: 0.87, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '药草' },
      { x: 0.51, y: 0.35, type: '灵木' },
      { x: 0.95, y: 0.63, type: '灵木' },
      { x: 0.3, y: 0.09, type: '矿脉' },
      { x: 0.73, y: 0.38, type: '药草' },
      { x: 0.07, y: 0.92, type: '灵木' },
      { x: 0.5, y: 0.08, type: '矿脉' },
      { x: 0.95, y: 0.34, type: '灵脉' },
      { x: 0.28, y: 0.92, type: '药草' },
      { x: 0.75, y: 0.09, type: '灵木' },
      { x: 0.05, y: 0.65, type: '灵木' },
      { x: 0.49, y: 0.91, type: '矿脉' },
      { x: 0.95, y: 0.08, type: '药草' },
      { x: 0.25, y: 0.67, type: '灵木' },
      { x: 0.72, y: 0.92, type: '矿脉' },
      { x: 0.05, y: 0.38, type: '灵脉' },
      { x: 0.5, y: 0.65, type: '药草' },
      { x: 0.92, y: 0.9, type: '灵木' },
      { x: 0.25, y: 0.37, type: '灵木' },
      { x: 0.72, y: 0.67, type: '矿脉' },
      { x: 0.05, y: 0.08, type: '药草' },
      { x: 0.5, y: 0.37, type: '灵木' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 20, targetX: 0.9, targetY: 0.5 },
    ],
  };
