// Region 6 — 草鹿
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone06: ZoneConfig = {
    id: 6, name: '草鹿',
    groundColor: 0x776644, roadColor: 0x998866, treeColor: 0x554422,
    decorations: [
      { type: 'house', x: 0.3, y: 0.35, w: 120, h: 90 },
      { type: 'house', x: 0.6, y: 0.55, w: 110, h: 85 },
      { type: 'pond', x: 0.45, y: 0.2, w: 80, h: 60 },
    ],
    npcs: [
      { x: 0.45, y: 0.35, name: '草鹿八千流', role: 'merchant', dialogue: [
        { speaker: '草鹿八千流', text: '这里是草鹿！剑剑大人让我管装备。想要好东西？先付钱！', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(3, '草鹿', ['kusa_hat', 'kusa_armor', 'kusa_bracer', 'kusa_boots', 'kusa_belt', 'kusa_ring', 'kusa_necklace', 'kusa_charm', 'kusa_pendant']) },
      { x: 0.7, y: 0.5, name: '更木剑八', role: 'quest', dialogue: [
        { speaker: '更木剑八', text: '喂！新人。始解的试炼？跟我打一场就知道了。不过先帮我找几个强敌热热身。', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '太强了…', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '草鹿的传送据点。北边通往静灵庭。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '草鹿磨刀匠', role: 'enhance', dialogue: [{ speaker: '草鹿磨刀匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '卯之花烈', role: 'side_quest', dialogue: [
        { speaker: '卯之花烈', text: '你的灵压有些紊乱。帮我收集灵脉样本调制药剂。' },
      ]},
      { x: 0.65, y: 0.8, name: '涅茧利', role: 'side_quest', dialogue: [
        { speaker: '涅茧利', text: '我对你的力量构成很感兴趣。帮我击败几只大虚，收集战斗数据。' },
      ]},
      { x: 0.15, y: 0.5, name: '日番谷冬狮郎', role: 'lore', dialogue: [
        { speaker: '日番谷冬狮郎', text: '始解完成了？很好。北边的静灵庭——卍解的试炼在那里。' },
        { speaker: '日番谷冬狮郎', text: '但别急。先把流魂街的虚清理干净。草鹿是最靠近静灵庭的流魂街区。' },
      ]},
      { x: 0.8, y: 0.65, name: '松本乱菊', role: 'lore', dialogue: [
        { speaker: '松本乱菊', text: '修行好累……不过市丸银曾经在这里出现过。' },
        { speaker: '松本乱菊', text: '静灵庭在北边。日番谷大队长在等有资格参加卍解试炼的人。' },
      ]},
    ],
    enemies: [

      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.93, y: 0.95 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.19, y: 0.93 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.35, y: 0.78 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.55, y: 0.81 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.2, y: 0.3 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.7, y: 0.4 },
      // ── 区域Boss（琪露诺） ──
      { name: '琪露诺', type: '妖将', element: '雷', x: 0.93, y: 0.88, isBoss: true },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.05, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.53, y: 0.34 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.94, y: 0.62 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.25, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.73, y: 0.34 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.06, y: 0.9 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.52, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.93, y: 0.34 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.3, y: 0.92 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.71, y: 0.1 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.66 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.47, y: 0.91 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.93, y: 0.08 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.25, y: 0.64 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.7, y: 0.92 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.08, y: 0.36 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.51, y: 0.65 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.27, y: 0.37 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.71, y: 0.64 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.48, y: 0.35 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.67 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.27, y: 0.08 },
      { name: '武装暴徒', type: '杂妖', element: '土', x: 0.74, y: 0.34 },
      { name: '暴走虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.91 },
      { name: '叛逆队员·长', type: '杂妖', element: '无', x: 0.47, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.95, y: 0.34 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.25, y: 0.92 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.72, y: 0.08 },
      { name: '大虚·基利安', type: '恶妖', element: '无', x: 0.05, y: 0.61 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.53, y: 0.91 },
    ],
    gathering: [
      { x: 0.93, y: 0.1, type: '药草' },
      { x: 0.59, y: 0.6, type: '灵脉' },
      { x: 0.79, y: 0.91, type: '灵木' },
      { x: 0.12, y: 0.34, type: '矿脉' },
      { x: 0.21, y: 0.19, type: '药草' },
      { x: 0.21, y: 0.27, type: '矿脉' },
      { x: 0.9, y: 0.73, type: '灵脉' },
      { x: 0.58, y: 0.28, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '药草' },
      { x: 0.51, y: 0.35, type: '灵脉' },
      { x: 0.95, y: 0.66, type: '灵木' },
      { x: 0.26, y: 0.08, type: '矿脉' },
      { x: 0.71, y: 0.34, type: '药草' },
      { x: 0.05, y: 0.92, type: '矿脉' },
      { x: 0.53, y: 0.1, type: '灵脉' },
      { x: 0.95, y: 0.36, type: '灵脉' },
      { x: 0.25, y: 0.92, type: '药草' },
      { x: 0.72, y: 0.08, type: '灵脉' },
      { x: 0.05, y: 0.62, type: '灵木' },
      { x: 0.48, y: 0.91, type: '矿脉' },
      { x: 0.94, y: 0.1, type: '药草' },
      { x: 0.26, y: 0.65, type: '矿脉' },
      { x: 0.74, y: 0.92, type: '灵脉' },
      { x: 0.06, y: 0.37, type: '灵脉' },
      { x: 0.48, y: 0.65, type: '药草' },
      { x: 0.95, y: 0.92, type: '灵脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 5, targetX: 0.9, targetY: 0.5 },
      { edge: 'north', x: 0.5, y: 0.03, targetZone: 7, targetX: 0.5, targetY: 0.95 },
    ],
  };
