// Region 8 — 技术開発局
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone08: ZoneConfig = {
    id: 8, name: '技术開発局',
    backgroundImage: 'bg_zone_08',
    backgroundMode: 'cover',
    groundColor: 0x999988,
    npcs: [
      { x: 0.45, y: 0.35, id: 'npc_m08', name: '巧手商', role: 'merchant', dialogue: [
        { speaker: '巧手商', text: '技术开发局的装备——全都是最新研究成果。哼，别弄坏了。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(4, '技術局', ['tech_hat', 'tech_armor', 'tech_bracer', 'tech_boots', 'tech_belt', 'tech_ring', 'tech_necklace', 'tech_charm', 'tech_pendant']) },
      { x: 0.7, y: 0.5, id: 'npc_q07', name: '静言', role: 'quest', dialogue: [
        { speaker: '静言', text: '父亲大人的虚化研究有了突破。帮我收集一些灵脉样本，我让你看数据。', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, id: 'sys_return', name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '技术开发局的传送门。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.7, y: 0.45, id: 'sys_board', name: '任务公告板', role: 'quest_board', dialogue: [
        { speaker: '任务公告板', text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f08', name: '技开工', role: 'enhance', dialogue: [{ speaker: '技开工', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, id: 'npc_s24', name: '近卫', role: 'side_quest', dialogue: [
        { speaker: '近卫', text: '义骸的技术需要灵木。帮我采集5个灵木，我给你技术局的特制装备。' },
      ]},
      { x: 0.65, y: 0.8, id: 'npc_s25', name: '鸦鸣', role: 'side_quest', dialogue: [
        { speaker: '鸦鸣', text: '叛逆死神偷了我们的研究资料！帮我抢回来——击败几只就行。' },
      ]},
      { x: 0.15, y: 0.5, id: 'npc_m01', name: '云行商', role: 'lore', dialogue: [
        { speaker: '云行商', text: '我曾经也是技术开发局局长。虚化——是我最早的研究成果。' },
        { speaker: '云行商', text: '东边的真央灵术院有卍解的最终试炼。完成后再去虚圈。' },
      ]},
      { x: 0.8, y: 0.65, id: 'npc_s21', name: '冬凌', role: 'lore', dialogue: [
        { speaker: '冬凌', text: '卍解的试炼快完成了。去真央灵术院完成最后的修行。' },
        { speaker: '冬凌', text: '虚圈在更东边。那里有虚化的觉醒——但你必须先掌握卍解。' },
      ]},

    ],
    enemies: [

      { name: '护廷队士', type: '杂妖', element: '无', x: 0.21, y: 0.43 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.8, y: 0.58 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.1, y: 0.43 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.15, y: 0.09 },
      { name: '叛逆死神·长', type: '恶妖', element: '无', x: 0.6, y: 0.7 },
      // ── 区域Boss（涅茧利） ──
      { name: '涅茧利', type: '妖将', element: '毒', x: 0.93, y: 0.88, isBoss: true },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.07, y: 0.11 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.47, y: 0.38 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.93, y: 0.61 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.27, y: 0.09 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.7, y: 0.37 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.49, y: 0.09 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.37 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.27, y: 0.9 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.72, y: 0.1 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.05, y: 0.63 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.49, y: 0.91 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.25, y: 0.64 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.74, y: 0.89 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.37 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.5, y: 0.66 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.26, y: 0.36 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.75, y: 0.62 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.07, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.52, y: 0.37 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.94, y: 0.66 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.25, y: 0.09 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.75, y: 0.34 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.89 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.5, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.93, y: 0.35 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.27, y: 0.9 },
      { name: '叛逆死神·长', type: '恶妖', element: '无', x: 0.73, y: 0.08 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.05, y: 0.62 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.48, y: 0.92 },
      { name: '叛逆死神·长', type: '恶妖', element: '无', x: 0.94, y: 0.11 },
    ],
    gathering: [
      { x: 0.39, y: 0.08, type: '药草' },
      { x: 0.42, y: 0.17, type: '矿脉' },
      { x: 0.29, y: 0.43, type: '灵脉' },
      { x: 0.81, y: 0.67, type: '灵木' },
      { x: 0.12, y: 0.65, type: '灵木' },
      { x: 0.75, y: 0.12, type: '灵木' },
      { x: 0.94, y: 0.42, type: '灵木' },
      { x: 0.81, y: 0.21, type: '矿脉' },
      { x: 0.08, y: 0.08, type: '药草' },
      { x: 0.51, y: 0.34, type: '矿脉' },
      { x: 0.94, y: 0.67, type: '灵脉' },
      { x: 0.26, y: 0.08, type: '灵木' },
      { x: 0.73, y: 0.36, type: '灵木' },
      { x: 0.06, y: 0.92, type: '灵木' },
      { x: 0.49, y: 0.11, type: '灵木' },
      { x: 0.95, y: 0.36, type: '矿脉' },
      { x: 0.28, y: 0.92, type: '药草' },
      { x: 0.7, y: 0.09, type: '矿脉' },
      { x: 0.05, y: 0.62, type: '灵脉' },
      { x: 0.48, y: 0.89, type: '灵木' },
      { x: 0.92, y: 0.08, type: '灵木' },
      { x: 0.29, y: 0.61, type: '灵木' },
      { x: 0.75, y: 0.91, type: '灵木' },
      { x: 0.08, y: 0.33, type: '矿脉' },
      { x: 0.53, y: 0.66, type: '药草' },
      { x: 0.94, y: 0.92, type: '矿脉' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 7, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 9, targetX: 0.08, targetY: 0.5 },
    ],
  };
