// Region 7 — 一番队舍
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone07: ZoneConfig = {
    id: 7, name: '一番队舍',
    backgroundImage: 'bg_zone_07',
    backgroundMode: 'cover',
    groundColor: 0x888877,
    npcs: [
      { x: 0.7, y: 0.5, name: '朽木白哉', role: 'merchant', dialogue: [
        { speaker: '朽木白哉', text: '朽木家的装备都是精工打造。不便宜，但值得。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(4, '护廷', ['bronze_hat', 'bronze_armor', 'bronze_bracer', 'bronze_boots', 'bronze_belt', 'silver_ring', 'crystal_necklace', 'bronze_charm', 'wind_pendant']) },
      { x: 0.45, y: 0.25, name: '山本元柳斋', role: 'lore', dialogue: [
        { speaker: '山本元柳斋', text: '年轻人，你手中的斩魄刀已经完成了始解。但真正的力量——卍解——需要更深的觉悟。' },
        { speaker: '山本元柳斋', text: '卍解的力量足以毁灭一切。必须在静灵庭通过极限试炼才能掌握。' },
      ]},
      { x: 0.2, y: 0.7, name: '日番谷冬狮郎', role: 'quest', dialogue: [
        { speaker: '日番谷冬狮郎', text: '你完成了始解？很好。现在面对卍解的试炼——在极限中突破自己。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.85, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '静灵庭的传送门。通往虚圈的门在技术开发局方向。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '一番队锻造师', role: 'enhance', dialogue: [{ speaker: '一番队锻造师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.8, y: 0.2, name: '松本乱菊', role: 'side_quest', dialogue: [
        { speaker: '松本乱菊', text: '修行好累……帮我收集5株药草和2个灵木，我请你喝酒。' },
      ]},
      { x: 0.35, y: 0.15, name: '更木剑八', role: 'side_quest', dialogue: [
        { speaker: '更木剑八', text: '喂！跟我打一场！……不过先帮我找几个强敌热热身。' },
      ]},
      { x: 0.1, y: 0.45, name: '京乐春水', role: 'lore', dialogue: [
        { speaker: '京乐春水', text: '卍解啊……那可是相当危险的东西。总队长大人就从来不随便展示。' },
        { speaker: '京乐春水', text: '虚圈在东边。去那里之前，先确保你的卍解已经稳定。' },
      ]},
      { x: 0.55, y: 0.75, name: '卯之花烈', role: 'lore', dialogue: [
        { speaker: '卯之花烈', text: '卍解是斩魄刀的完全解放。它会让你的灵压成倍增长。' },
        { speaker: '卯之花烈', text: '但代价是巨大的消耗。技术开发局在东边——涅茧利有关于虚化的研究。' },
      ]},
    ],
    enemies: [

      { name: '护廷队士', type: '杂妖', element: '无', x: 0.3, y: 0.2 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.7, y: 0.4 }, { name: '叛逆死神', type: '恶妖', element: '无', x: 1.5, y: 0.3 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 1.8, y: 0.7 }, { name: '虚群', type: '杂妖', element: '无', x: 2.3, y: 0.6 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.5, y: 0.7 }, { name: '叛逆死神', type: '恶妖', element: '无', x: 2.7, y: 0.4 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 2.0, y: 0.15 },
      // ── 区域Boss（虚·噬魂） ──
      { name: '虚·噬魂(原创)', type: '妖将', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.48, y: 0.39 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.95, y: 0.61 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.3, y: 0.08 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.7, y: 0.34 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.5, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.37 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.27, y: 0.92 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.75, y: 0.08 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.06, y: 0.64 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.52, y: 0.92 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.28, y: 0.62 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.73, y: 0.92 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.37 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.51, y: 0.64 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.95, y: 0.9 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.28, y: 0.37 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.72, y: 0.65 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.05, y: 0.09 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.48, y: 0.33 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.95, y: 0.67 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.27, y: 0.1 },
      { name: '护廷队士', type: '杂妖', element: '无', x: 0.75, y: 0.36 },
      { name: '虚群', type: '杂妖', element: '无', x: 0.05, y: 0.91 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.48, y: 0.08 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.93, y: 0.39 },
      { name: '叛逆死神', type: '恶妖', element: '无', x: 0.25, y: 0.92 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.7, y: 0.1 },
    ],
    gathering: [
      { x: 0.1, y: 0.2, type: '矿脉' },
      { x: 0.3, y: 0.6, type: '药草' },
      { x: 0.5, y: 0.15, type: '灵木' },
      { x: 0.7, y: 0.8, type: '矿脉' },
      { x: 0.9, y: 0.45, type: '药草' },
      { x: 1.2, y: 0.7, type: '灵木' },
      { x: 1.5, y: 0.25, type: '矿脉' },
      { x: 1.9, y: 0.55, type: '药草' },
      { x: 2.2, y: 0.15, type: '灵木' },
      { x: 2.5, y: 0.8, type: '矿脉' },
      { x: 0.4, y: 0.45, type: '灵脉' },
      { x: 1.7, y: 0.35, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '矿脉' },
      { x: 0.51, y: 0.35, type: '药草' },
      { x: 0.95, y: 0.63, type: '灵木' },
      { x: 0.28, y: 0.08, type: '矿脉' },
      { x: 0.75, y: 0.36, type: '药草' },
      { x: 0.07, y: 0.92, type: '灵木' },
      { x: 0.49, y: 0.08, type: '矿脉' },
      { x: 0.94, y: 0.34, type: '药草' },
      { x: 0.3, y: 0.91, type: '灵木' },
      { x: 0.74, y: 0.1, type: '矿脉' },
      { x: 0.07, y: 0.66, type: '灵脉' },
      { x: 0.47, y: 0.92, type: '灵脉' },
      { x: 0.95, y: 0.1, type: '矿脉' },
      { x: 0.26, y: 0.66, type: '药草' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 6, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 8, targetX: 0.08, targetY: 0.5 },
    ],
  };
