// Region 14 — XCUTION基地
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone14: ZoneConfig = {
    id: 14, name: 'XCUTION基地',
    backgroundImage: 'bg_zone_14',
    backgroundMode: 'cover',
    groundColor: 0x445588,
    npcs: [
      { x: 0.45, y: 0.35, name: '银城空吾', role: 'merchant', dialogue: [
        { speaker: '银城空吾', text: 'XCUTION基地的装备——完现术强化的最高水平。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(7, 'XCUTION', ['xcution_hat', 'xcution_armor', 'xcution_bracer', 'xcution_boots', 'xcution_belt', 'xcution_ring', 'xcution_necklace', 'xcution_charm', 'xcution_pendant']) },
      { x: 0.7, y: 0.5, name: '毒峰莉露卡', role: 'quest', dialogue: [
        { speaker: '毒峰莉露卡', text: '完现术的第二阶段——你需要将物质的灵魂完全融合。来试试！', choices: [
          { text: '接受任务', callback: 'acceptQuest' }, { text: '稍等', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: 'XCUTION基地的传送门。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: 'XCUTION工匠', role: 'enhance', dialogue: [{ speaker: 'XCUTION工匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '贾姬', role: 'side_quest', dialogue: [
        { speaker: '贾姬', text: '完现术修行需要灵木。帮我收集，我教你"泥娃娃"的技巧。' },
      ]},
      { x: 0.65, y: 0.8, name: '雪绪', role: 'side_quest', dialogue: [
        { speaker: '雪绪', text: '完现者(敌)越来越强了。帮我击败几只精英，我给你游戏特权。' },
      ]},
      { x: 0.15, y: 0.5, name: '茶渡泰虎', role: 'lore', dialogue: [
        { speaker: '茶渡泰虎', text: '我的右臂——"巨人的一击"。完现术让我的力量更稳定了。' },
        { speaker: '茶渡泰虎', text: '东边的完现术总本山——那里有最终试炼。完成后再去无形帝国。' },
      ]},
      { x: 0.8, y: 0.65, name: '月岛秀九郎(残影)', role: 'lore', dialogue: [
        { speaker: '月岛秀九郎(残影)', text: '完现术的本质——灵魂注入物质。你的斩魄刀也是灵魂的具现化。' },
        { speaker: '月岛秀九郎(残影)', text: '无形帝国的灭却师……他们用"圣文字"而不是斩魄刀。完全不同的力量体系。' },
      ]},
    ],
    enemies: [

      { name: '完现虚', type: '杂妖', element: '无', x: 0.27, y: 0.22 },
      { name: '完现者(敌)', type: '恶妖', element: '无', x: 0.34, y: 0.46 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.2, y: 0.92 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.53, y: 0.9 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.3 },
      // ── 区域Boss（银城空吾） ──
      { name: '银城空吾', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.07, y: 0.11 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.49, y: 0.39 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.95, y: 0.66 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.25, y: 0.08 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.72, y: 0.36 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.06, y: 0.92 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.48, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.36 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.29, y: 0.92 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.08 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.05, y: 0.62 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.48, y: 0.91 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.26, y: 0.61 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.72, y: 0.92 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.05, y: 0.38 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.5, y: 0.66 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.94, y: 0.9 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.3, y: 0.38 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.7, y: 0.64 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.05, y: 0.1 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.53, y: 0.33 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.95, y: 0.61 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.29, y: 0.08 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.73, y: 0.36 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.07, y: 0.92 },
      { name: '完现虚', type: '杂妖', element: '无', x: 0.53, y: 0.1 },
      { name: '完现虚·改', type: '杂妖', element: '无', x: 0.95, y: 0.34 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.3, y: 0.92 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.75, y: 0.08 },
      { name: '完现者(敌)', type: '恶妖', element: '无', x: 0.06, y: 0.67 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.47, y: 0.92 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.95, y: 0.09 },
      { name: '完现者(敌)', type: '恶妖', element: '无', x: 0.28, y: 0.67 },
      { name: '大虚·亚丘卡斯', type: '恶妖', element: '无', x: 0.74, y: 0.9 },
      { name: '完现者·长', type: '恶妖', element: '无', x: 0.05, y: 0.33 },
      { name: '完现者(敌)', type: '恶妖', element: '无', x: 0.5, y: 0.61 },
    ],
    gathering: [
      { x: 0.15, y: 0.56, type: '灵木' },
      { x: 0.67, y: 0.35, type: '药草' },
      { x: 0.08, y: 0.37, type: '灵木' },
      { x: 0.06, y: 0.07, type: '药草' },
      { x: 0.65, y: 0.14, type: '灵木' },
      { x: 0.62, y: 0.82, type: '药草' },
      { x: 0.81, y: 0.36, type: '矿脉' },
      { x: 0.72, y: 0.19, type: '灵木' },
      { x: 0.05, y: 0.08, type: '灵木' },
      { x: 0.48, y: 0.36, type: '药草' },
      { x: 0.95, y: 0.65, type: '灵木' },
      { x: 0.3, y: 0.1, type: '药草' },
      { x: 0.74, y: 0.36, type: '灵木' },
      { x: 0.05, y: 0.92, type: '药草' },
      { x: 0.48, y: 0.08, type: '矿脉' },
      { x: 0.93, y: 0.38, type: '灵木' },
      { x: 0.28, y: 0.91, type: '灵木' },
      { x: 0.71, y: 0.1, type: '药草' },
      { x: 0.06, y: 0.63, type: '灵木' },
      { x: 0.52, y: 0.92, type: '药草' },
      { x: 0.94, y: 0.1, type: '灵木' },
      { x: 0.29, y: 0.67, type: '药草' },
      { x: 0.75, y: 0.9, type: '矿脉' },
      { x: 0.06, y: 0.37, type: '灵木' },
      { x: 0.5, y: 0.63, type: '灵木' },
      { x: 0.95, y: 0.91, type: '药草' },
      { x: 0.29, y: 0.38, type: '灵木' },
      { x: 0.75, y: 0.62, type: '药草' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 13, targetX: 0.9, targetY: 0.5 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 15, targetX: 0.08, targetY: 0.5 },
    ],
  };
