// Region 12 — 虚夜宫
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone12: ZoneConfig = {
    id: 12, name: '虚夜宫',
    backgroundImage: 'bg_zone_12',
    backgroundMode: 'cover',
    groundColor: 0x666677,
    npcs: [
      { x: 0.45, y: 0.35, name: '赫丽贝尔', role: 'merchant', dialogue: [
        { speaker: '赫丽贝尔', text: '虚夜宫的装备——顶级的破面锻造品。蓝染大人走后，这些都归我了。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(6, '虚夜', ['noches_hat', 'noches_armor', 'noches_bracer', 'noches_boots', 'noches_belt', 'noches_ring', 'noches_necklace', 'noches_charm', 'noches_pendant']) },
      { x: 0.7, y: 0.5, name: '葛力姆乔(残影)', role: 'quest', dialogue: [
        { speaker: '葛力姆乔(残影)', text: '虚化的最终试炼——在虚夜宫的最深处释放你的虚。打败我！', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.85, y: 0.2, name: '黑腔', role: 'return_point', dialogue: [
        { speaker: '黑腔', text: '虚夜宫的黑腔出口。北边通往现世。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '虚夜宫兵器师', role: 'enhance', dialogue: [{ speaker: '虚夜宫兵器师', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.2, y: 0.7, name: '牙密', role: 'side_quest', dialogue: [
        { speaker: '牙密', text: '虚夜宫的守卫越来越少了。帮我击败几只叛逆破面。' },
      ]},
      { x: 0.65, y: 0.8, name: '妮露', role: 'side_quest', dialogue: [
        { speaker: '妮露', text: '虚夜宫的灵脉被污染了。帮我采集干净的灵脉，净化这里。' },
      ]},
      { x: 0.15, y: 0.5, name: '乌尔奇奥拉(残影)', role: 'lore', dialogue: [
        { speaker: '乌尔奇奥拉(残影)', text: '虚化完成了。但你的旅途还没结束——现世有新的力量等你。' },
        { speaker: '乌尔奇奥拉(残影)', text: '完现术——将物质中的灵魂觉醒化为己用。北边的穿界门通往现世。' },
      ]},
      { x: 0.8, y: 0.65, name: '蓝染惣右介(残影)', role: 'lore', dialogue: [
        { speaker: '蓝染惣右介(残影)', text: '一切都是镜花水月……你以为虚化是你选择的路？不，是命运选择了你。' },
        { speaker: '蓝染惣右介(残影)', text: '现世的XCUTION……完现术者的组织。他们在等你。但无形帝国的威胁更近了。' },
      ]},
    ],
    enemies: [

      { name: '破面·上级', type: '恶妖', element: '无', x: 0.38, y: 0.54 },
      { name: '亚丘卡斯·改', type: '恶妖', element: '无', x: 0.32, y: 0.47 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.79, y: 0.25 },
      { name: '瓦史托德', type: '恶妖', element: '无', x: 0.95, y: 0.79 },
      { name: '破面·上级', type: '恶妖', element: '无', x: 0.5, y: 0.8 },
      // ── 区域Boss（诺伊特拉） ──
      { name: '诺伊特拉', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.52, y: 0.38 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.92, y: 0.63 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.26, y: 0.09 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.72, y: 0.34 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.51, y: 0.08 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.95, y: 0.36 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.25, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.71, y: 0.09 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.07, y: 0.62 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.49, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.95, y: 0.1 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.25, y: 0.67 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.74, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.06, y: 0.37 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.49, y: 0.64 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.95, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.3, y: 0.33 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.72, y: 0.62 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.47, y: 0.34 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.92, y: 0.65 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.25, y: 0.1 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.75, y: 0.38 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.05, y: 0.92 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.51, y: 0.08 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.93, y: 0.33 },
      { name: '基利安群', type: '杂妖', element: '无', x: 0.26, y: 0.92 },
      { name: '瓦史托德', type: '恶妖', element: '无', x: 0.75, y: 0.08 },
      { name: '破面·上级', type: '恶妖', element: '无', x: 0.05, y: 0.67 },
      { name: '亚丘卡斯·改', type: '恶妖', element: '无', x: 0.49, y: 0.89 },
      { name: '瓦史托德', type: '恶妖', element: '无', x: 0.95, y: 0.1 },
      { name: '破面·上级', type: '恶妖', element: '无', x: 0.28, y: 0.61 },
      { name: '亚丘卡斯·改', type: '恶妖', element: '无', x: 0.75, y: 0.9 },
      { name: '瓦史托德', type: '恶妖', element: '无', x: 0.07, y: 0.36 },
      { name: '破面·上级', type: '恶妖', element: '无', x: 0.51, y: 0.62 },
    ],
    gathering: [
      { x: 0.9, y: 0.09, type: '矿脉' },
      { x: 0.78, y: 0.49, type: '灵木' },
      { x: 0.37, y: 0.32, type: '灵脉' },
      { x: 0.58, y: 0.54, type: '药草' },
      { x: 0.69, y: 0.91, type: '灵脉' },
      { x: 0.19, y: 0.32, type: '矿脉' },
      { x: 0.72, y: 0.77, type: '药草' },
      { x: 0.14, y: 0.06, type: '灵脉' },
      { x: 0.05, y: 0.09, type: '矿脉' },
      { x: 0.53, y: 0.34, type: '灵木' },
      { x: 0.95, y: 0.61, type: '灵脉' },
      { x: 0.26, y: 0.08, type: '药草' },
      { x: 0.75, y: 0.34, type: '灵脉' },
      { x: 0.05, y: 0.92, type: '矿脉' },
      { x: 0.48, y: 0.08, type: '药草' },
      { x: 0.95, y: 0.37, type: '灵脉' },
      { x: 0.29, y: 0.9, type: '矿脉' },
      { x: 0.7, y: 0.08, type: '灵木' },
      { x: 0.05, y: 0.67, type: '灵脉' },
      { x: 0.48, y: 0.91, type: '药草' },
      { x: 0.94, y: 0.08, type: '灵脉' },
      { x: 0.29, y: 0.67, type: '矿脉' },
      { x: 0.75, y: 0.92, type: '药草' },
      { x: 0.08, y: 0.35, type: '灵脉' },
      { x: 0.51, y: 0.65, type: '矿脉' },
      { x: 0.95, y: 0.92, type: '灵木' },
      { x: 0.28, y: 0.38, type: '灵脉' },
      { x: 0.75, y: 0.62, type: '药草' },
    ],
    exits: [
      { edge: 'west', x: 0.03, y: 0.5, targetZone: 11, targetX: 0.9, targetY: 0.5 },
      { edge: 'north', x: 0.5, y: 0.03, targetZone: 13, targetX: 0.5, targetY: 0.95 },
    ],
  };
