// Region 13 — 战迹
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone13: ZoneConfig = {
    id: 13, name: '战迹',
    backgroundImage: 'bg_zone_13',
    backgroundMode: 'cover',
    groundColor: 0x445566,
    npcs: [
      { x: 0.55, y: 0.35, id: 'npc_m13', role: 'merchant', dialogue: [
        { speaker: '银镜坊', text: '完现术者的装备——利用身边的一切物质强化战斗。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(7, '显灵', ['scale_hat', 'scale_armor', 'scale_bracer', 'scale_boots', 'scale_belt', 'royal_ring', 'royal_necklace', 'royal_charm', 'windwalker_pendant']) },
      { x: 0.2, y: 0.7, id: 'npc_q11', role: 'quest', dialogue: [
        { speaker: '花铃', text: '欢迎回来——空座町还是老样子。想学完现术？找我吧。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.3, y: 0.2, id: 'sys_return', name: '穿界门', role: 'return_point', dialogue: [
        { speaker: '穿界门', text: '回到现世的穿界门。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, id: 'sys_craft', name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.75, id: 'sys_board', name: '任务公告板', role: 'quest_board', dialogue: [
        { speaker: '任务公告板', text: '今日与本周的委托都张贴在这里。完成它们能稳定获取金币与经验。', choices: [
          { text: '查看任务板', callback: 'openQuestBoard' }, { text: '离开', callback: 'closeDialogue' },
        ]},
      ]},
      { x: 0.55, y: 0.38, id: 'npc_f13', role: 'enhance', dialogue: [{ speaker: '战迹翁', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.85, y: 0.25, id: 'npc_s29', role: 'side_quest', dialogue: [
        { speaker: '电光', text: '我的靴子被虚咬坏了。帮我收集矿脉做双新的。' },
      ]},
      { x: 0.15, y: 0.5, id: 'npc_s30', role: 'side_quest', dialogue: [
        { speaker: '雪绪', text: '游戏需要数据。帮我击败几只完现虚收集战斗数据。' },
      ]},
      { x: 0.8, y: 0.6, id: 'npc_q12', role: 'lore', dialogue: [
        { speaker: '残影·墨', text: '完现术——将物质中的灵魂觉醒化为己用的力量。我曾经的"终结之书"能改写一切。' },
        { speaker: '残影·墨', text: '无形帝国在东边。他们自称灭却师的后裔。圣文字的力量……非常危险。' },
      ]},
      { x: 0.45, y: 0.6, id: 'npc_s28', role: 'lore', dialogue: [
        { speaker: '雨龙', text: '灭却师和死神的本质不同。无形帝国的敌人……他们用的是"圣文字"。' },
        { speaker: '雨龙', text: 'XCUTION基地在东边。银城在那里等你。但真正的敌人——无形帝国——更东边。' },
      ]},

    ],
    enemies: [

      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.3, y: 0.2 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.6, y: 0.45 }, { name: 'm_fb_void', type: '杂妖', element: '无', x: 1.2, y: 0.7 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 1.7, y: 0.3 }, { name: 'm_adjuchas_boss', type: '恶妖', element: '无', x: 2.2, y: 0.55 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 2.5, y: 0.25 }, { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.2, y: 0.8 },
      { name: 'm_adjuchas_boss', type: '恶妖', element: '无', x: 1.8, y: 0.8 }, { name: 'm_fb_void', type: '杂妖', element: '无', x: 2.8, y: 0.65 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.9, y: 0.15 },
      // ── 区域Boss（扎艾尔阿波罗） ──
      { name: 'b_szayel', type: '妖王', element: '毒', x: 0.93, y: 0.88, isBoss: true },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.07, y: 0.08 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.49, y: 0.39 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.93, y: 0.66 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.3, y: 0.09 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.71, y: 0.38 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.05, y: 0.91 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.53, y: 0.09 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.95, y: 0.39 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.29, y: 0.92 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.73, y: 0.08 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.07, y: 0.66 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.5, y: 0.92 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.95, y: 0.09 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.27, y: 0.61 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.74, y: 0.92 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.07, y: 0.38 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.48, y: 0.63 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.94, y: 0.89 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.28, y: 0.37 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.74, y: 0.66 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.07, y: 0.11 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.52, y: 0.33 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.93, y: 0.61 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.25, y: 0.08 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.73, y: 0.37 },
      { name: 'm_fb_void', type: '杂妖', element: '无', x: 0.07, y: 0.9 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.47, y: 0.08 },
      { name: 'm_adjuchas_boss', type: '恶妖', element: '无', x: 0.93, y: 0.33 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.25, y: 0.92 },
      { name: 'm_adjuchas_boss', type: '恶妖', element: '无', x: 0.72, y: 0.08 },
      { name: 'm_fb_foe', type: '恶妖', element: '无', x: 0.07, y: 0.61 },
      { name: 'm_adjuchas_boss', type: '恶妖', element: '无', x: 0.49, y: 0.89 },
    ],
    gathering: [
      { x: 0.1, y: 0.25, type: '矿脉' },
      { x: 0.3, y: 0.55, type: '灵木' },
      { x: 0.55, y: 0.3, type: '药草' },
      { x: 0.8, y: 0.7, type: '矿脉' },
      { x: 1.1, y: 0.4, type: '灵木' },
      { x: 1.4, y: 0.2, type: '药草' },
      { x: 1.7, y: 0.6, type: '矿脉' },
      { x: 2, y: 0.35, type: '灵木' },
      { x: 2.4, y: 0.7, type: '药草' },
      { x: 2.7, y: 0.2, type: '矿脉' },
      { x: 0.5, y: 0.65, type: '灵脉' },
      { x: 2.2, y: 0.85, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '矿脉' },
      { x: 0.53, y: 0.39, type: '灵木' },
      { x: 0.95, y: 0.66, type: '药草' },
      { x: 0.25, y: 0.08, type: '矿脉' },
      { x: 0.73, y: 0.34, type: '灵木' },
      { x: 0.06, y: 0.92, type: '药草' },
      { x: 0.48, y: 0.08, type: '矿脉' },
      { x: 0.95, y: 0.33, type: '灵木' },
      { x: 0.25, y: 0.92, type: '药草' },
      { x: 0.71, y: 0.09, type: '矿脉' },
      { x: 0.05, y: 0.66, type: '灵脉' },
      { x: 0.52, y: 0.92, type: '灵脉' },
      { x: 0.95, y: 0.11, type: '矿脉' },
      { x: 0.26, y: 0.62, type: '灵木' },
      { x: 0.75, y: 0.91, type: '药草' },
      { x: 0.07, y: 0.36, type: '矿脉' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 12, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 14, targetX: 0.08, targetY: 0.5 },
    ],
  };
