// Region 19 — 咎人之门
import type { ZoneConfig } from './types';
import { shop } from './shop';
  export const zone19: ZoneConfig = {
    id: 19, name: '咎人之门',
    groundColor: 0x1a1118, roadColor: 0x332228, treeColor: 0x0a0810,
    decorations: [
      { type: 'pond', x: 0.3, y: 0.3, w: 160, h: 100 },
      { type: 'house', x: 0.15, y: 0.5, w: 100, h: 70 },
      { type: 'house', x: 0.8, y: 0.35, w: 90, h: 65 },
    ],
    npcs: [
      { x: 0.4, y: 0.3, name: '地狱看守', role: 'merchant', dialogue: [
        { speaker: '地狱看守', text: '这里是灵魂的终点。用尽了生命和力量的残骸……都是上好的材料。', choices: [{ text: '交易', callback: 'openShop' }] },
      ],
      shop: shop(10, '狱', ['abyss_hat', 'abyss_armor', 'abyss_bracer', 'abyss_boots', 'abyss_belt', 'dark_ring', 'abyss_necklace', 'abyss_charm', 'void_pendant']) },
      { x: 0.2, y: 0.65, name: '井上织姬(残影)', role: 'quest', dialogue: [
        { speaker: '井上织姬(残影)', text: '四力已经集齐。地狱最深处——终焉之兽在等你。击败它，完成你的试炼。', choices: [
          { text: '接受任务', callback: 'acceptQuest' },
        ]},
      ]},
      { x: 0.55, y: 0.55, name: '终焉之渊', role: 'return_point', dialogue: [
        { speaker: '地狱之门', text: '千年来从未开启的门——但你需要回去。', choices: [{ text: '使用传送', callback: 'openReturn' }] },
      ]},
      { x: 0.5, y: 0.3, name: '神奇的魔法阵', role: 'craft', dialogue: [
        { speaker: '魔法阵', text: '嗡……古老制造阵法的遗存。', choices: [{ text: '打开制造', callback: 'openCraft' }] },
      ]},
      { x: 0.55, y: 0.38, name: '咎人铁匠', role: 'enhance', dialogue: [{ speaker: '咎人铁匠', text: '装备的强化、精炼、分解都交给我吧。好的装备是战斗的基础。', choices: [{ text: '打开强化工坊', callback: 'openEnhance' }, { text: '离开', callback: 'closeDialogue' }] },] },
      { x: 0.8, y: 0.25, name: '地狱狱卒', role: 'side_quest', dialogue: [
        { speaker: '地狱狱卒', text: '咎人越狱了！帮我抓回5个，我给你地狱的秘宝。' },
      ]},
      { x: 0.35, y: 0.15, name: '被囚的灵魂', role: 'side_quest', dialogue: [
        { speaker: '被囚的灵魂', text: '我在这里太久了……帮我找一些矿脉，我想为自己刻一块墓碑。' },
      ]},
      { x: 0.15, y: 0.4, name: '茶渡泰虎(残影)', role: 'lore', dialogue: [
        { speaker: '茶渡泰虎(残影)', text: '一护曾经面对过终焉的力量。你呢——你能承受吗？' },
        { speaker: '茶渡泰虎(残影)', text: '地狱是所有灵魂的归宿。虚、死神、灭却师……最终都在这里。东边的无间更深。' },
      ]},
      { x: 0.7, y: 0.8, name: '守门人', role: 'lore', dialogue: [
        { speaker: '守门人', text: '狱解——地狱的最终力量。它会让你的伤害翻倍，但每回合消耗生命。' },
        { speaker: '守门人', text: '无间在东边。终焉之渊在更深处。那里有最终的敌人。' },
      ]},
    ],
    enemies: [

      { name: '咎人', type: '杂妖', element: '无', x: 0.25, y: 0.2 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.5, y: 0.45 }, { name: '咎人', type: '杂妖', element: '无', x: 0.8, y: 0.3 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 1.2, y: 0.55 }, { name: '地狱守卫', type: '恶妖', element: '土', x: 1.6, y: 0.25 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 2.0, y: 0.65 }, { name: '终焉之兽', type: '恶妖', element: '无', x: 2.4, y: 0.35 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 2.8, y: 0.7 }, { name: '地狱犬', type: '恶妖', element: '火', x: 0.15, y: 0.7 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 1.8, y: 0.85 },       { name: '咎人', type: '杂妖', element: '无', x: 0.6, y: 0.8 },
      // ── 区域Boss（黑刀） ──
      { name: '黑刀', type: '妖王', element: '无', x: 0.93, y: 0.88, isBoss: true },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.5, y: 0.38 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.95, y: 0.61 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.3, y: 0.11 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.72, y: 0.36 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.05, y: 0.9 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.53, y: 0.09 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.95, y: 0.34 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.27, y: 0.91 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.7, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.66 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.48, y: 0.92 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.95, y: 0.08 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.28, y: 0.62 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.73, y: 0.92 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.06, y: 0.36 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.53, y: 0.64 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.95, y: 0.91 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.26, y: 0.33 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.75, y: 0.65 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.05, y: 0.09 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.48, y: 0.34 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.95, y: 0.67 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.26, y: 0.08 },
      { name: '咎人', type: '杂妖', element: '无', x: 0.74, y: 0.34 },
      { name: '咎人·怨', type: '杂妖', element: '无', x: 0.07, y: 0.89 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.48, y: 0.08 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.95, y: 0.38 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.29, y: 0.92 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.75, y: 0.09 },
      { name: '地狱守卫', type: '恶妖', element: '土', x: 0.08, y: 0.61 },
      { name: '终焉之兽', type: '恶妖', element: '无', x: 0.51, y: 0.92 },
      { name: '地狱犬', type: '恶妖', element: '火', x: 0.92, y: 0.08 },
      { name: '混沌兽', type: '恶妖', element: '无', x: 0.25, y: 0.67 },
    ],
    gathering: [
      { x: 0.1, y: 0.3, type: '矿脉' },
      { x: 0.3, y: 0.55, type: '灵木' },
      { x: 0.55, y: 0.2, type: '药草' },
      { x: 0.8, y: 0.6, type: '矿脉' },
      { x: 1.1, y: 0.35, type: '灵木' },
      { x: 1.4, y: 0.75, type: '药草' },
      { x: 1.7, y: 0.45, type: '矿脉' },
      { x: 2, y: 0.2, type: '灵木' },
      { x: 2.3, y: 0.55, type: '药草' },
      { x: 2.6, y: 0.8, type: '矿脉' },
      { x: 0.5, y: 0.4, type: '灵脉' },
      { x: 2.2, y: 0.7, type: '灵脉' },
      { x: 0.05, y: 0.08, type: '矿脉' },
      { x: 0.5, y: 0.34, type: '灵木' },
      { x: 0.95, y: 0.66, type: '药草' },
      { x: 0.3, y: 0.09, type: '矿脉' },
      { x: 0.7, y: 0.39, type: '灵木' },
      { x: 0.07, y: 0.91, type: '药草' },
      { x: 0.51, y: 0.08, type: '矿脉' },
      { x: 0.95, y: 0.33, type: '灵木' },
      { x: 0.26, y: 0.92, type: '药草' },
      { x: 0.71, y: 0.08, type: '矿脉' },
      { x: 0.05, y: 0.66, type: '灵脉' },
      { x: 0.49, y: 0.92, type: '灵脉' },
      { x: 0.93, y: 0.08, type: '矿脉' },
      { x: 0.25, y: 0.62, type: '灵木' },
      { x: 0.73, y: 0.9, type: '药草' },
      { x: 0.05, y: 0.37, type: '矿脉' },
      { x: 0.52, y: 0.65, type: '灵木' },
      { x: 0.94, y: 0.92, type: '药草' },
    ],
    exits: [
      { edge: 'south', x: 0.5, y: 0.97, targetZone: 18, targetX: 0.5, targetY: 0.05 },
      { edge: 'east', x: 0.97, y: 0.5, targetZone: 20, targetX: 0.08, targetY: 0.5 },
    ],
  };
