// 扫描 public/assets/battlefx/*/ 下每个子目录的 atlas JSON，生成
// src/generated/battleFxManifest.ts。帧宽/高/帧数全部从美术资源自动读取，
// 不写死，因此美术改帧数/加资源后重新跑本脚本（或 predev/prebuild 自动跑）即可。
//
// 运行：node scripts/genBattleFxManifest.mjs  （package.json 已挂 predev / prebuild）
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const fxDir = join(root, 'public', 'assets', 'battlefx');

/** @type {Array<{key:string,pngFile:string,frameWidth:number,frameHeight:number,frameCount:number,url:string}>} */
const entries = [];

if (existsSync(fxDir)) {
  for (const folder of readdirSync(fxDir)) {
    const dir = join(fxDir, folder);
    if (!statSync(dir).isDirectory()) continue;

    const jsonName = readdirSync(dir).find((f) => f.toLowerCase().endsWith('.json'));
    if (!jsonName) {
      console.warn(`[genBattleFx] 跳过 ${folder}：缺少 atlas JSON`);
      continue;
    }

    let json;
    try {
      json = JSON.parse(readFileSync(join(dir, jsonName), 'utf-8'));
    } catch (e) {
      console.warn(`[genBattleFx] 跳过 ${folder}：JSON 解析失败 - ${e.message}`);
      continue;
    }

    const frames = (json && json.frames) || {};
    const keys = Object.keys(frames);
    if (keys.length === 0) {
      console.warn(`[genBattleFx] 跳过 ${folder}：frames 为空`);
      continue;
    }

    const first = frames[keys[0]].frame;
    const pngFile = (json.meta && json.meta.image) || jsonName.replace(/\.json$/i, '.png');

    entries.push({
      key: folder,
      pngFile,
      frameWidth: first.w,
      frameHeight: first.h,
      frameCount: keys.length,
      url: `assets/battlefx/${folder}/${pngFile}`,
    });
  }
}

entries.sort((a, b) => a.key.localeCompare(b.key));

const banner = `// AUTO-GENERATED by scripts/genBattleFxManifest.mjs — 勿手改。
// 美术在 public/assets/battlefx/ 下新增/替换资源后重新生成：npm run gen:fx
// （predev / prebuild 已自动跑）。帧宽/高/帧数均从美术 atlas JSON 自动读取。

export interface BattleFxEntry {
  /** clip 键，等于 battlefx 子目录名（如 "fx_fire_impact"）。 */
  key: string;
  /** 子目录内的精灵表 PNG 文件名。 */
  pngFile: string;
  /** 单帧宽（px，取自 atlas JSON）。 */
  frameWidth: number;
  /** 单帧高（px）。 */
  frameHeight: number;
  /** 总帧数。 */
  frameCount: number;
  /** Phaser 加载用的 URL（相对 public 根）。 */
  url: string;
}

export const BATTLE_FX_MANIFEST: BattleFxEntry[] = `;

const out = `${banner}${JSON.stringify(entries, null, 2)};\n`;

const genDir = join(root, 'src', 'generated');
if (!existsSync(genDir)) mkdirSync(genDir, { recursive: true });
writeFileSync(join(genDir, 'battleFxManifest.ts'), out, 'utf-8');

console.log(`[genBattleFx] 生成 ${entries.length} 条 battlefx 清单 -> src/generated/battleFxManifest.ts`);
for (const e of entries) {
  console.log(`  ${e.key.padEnd(22)} ${e.frameWidth}x${e.frameHeight} x${e.frameCount}  ${e.url}`);
}
